{-
   Ory Hydra API

   Documentation for all of Ory Hydra's APIs. 

   OpenAPI Version: 3.0.3
   Ory Hydra API API version: 
   Contact: hi@ory.sh
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : OryHydra.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module OryHydra.Logging
  ( module OryHydra.LoggingKatip
  ) where

import OryHydra.LoggingKatip

#else

module OryHydra.Logging
  ( module OryHydra.LoggingMonadLogger
  ) where

import OryHydra.LoggingMonadLogger

#endif
