{-
   ORY Hydra

   Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.

   OpenAPI Version: 3.0.1
   ORY Hydra API version: latest
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : ORYHydra.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module ORYHydra.Logging
  ( module ORYHydra.LoggingKatip
  ) where

import ORYHydra.LoggingKatip

#else

module ORYHydra.Logging
  ( module ORYHydra.LoggingMonadLogger
  ) where

import ORYHydra.LoggingMonadLogger

#endif
