{-
   Ory Hydra API

   Documentation for all of Ory Hydra's APIs. 

   OpenAPI Version: 3.0.3
   Ory Hydra API API version: 
   Contact: hi@ory.sh
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : OryHydra.Lens
-}

{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-matches -fno-warn-unused-binds -fno-warn-unused-imports #-}

module OryHydra.ModelLens where

import qualified Data.Aeson as A
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Data, Typeable)
import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Data.Time as TI

import Data.Text (Text)

import Prelude (($), (.),(<$>),(<*>),(=<<),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

import OryHydra.Model
import OryHydra.Core


-- * AcceptOAuth2ConsentRequest

-- | 'acceptOAuth2ConsentRequestGrantAccessTokenAudience' Lens
acceptOAuth2ConsentRequestGrantAccessTokenAudienceL :: Lens_' AcceptOAuth2ConsentRequest (Maybe [Text])
acceptOAuth2ConsentRequestGrantAccessTokenAudienceL f AcceptOAuth2ConsentRequest{..} = (\acceptOAuth2ConsentRequestGrantAccessTokenAudience -> AcceptOAuth2ConsentRequest { acceptOAuth2ConsentRequestGrantAccessTokenAudience, ..} ) <$> f acceptOAuth2ConsentRequestGrantAccessTokenAudience
{-# INLINE acceptOAuth2ConsentRequestGrantAccessTokenAudienceL #-}

-- | 'acceptOAuth2ConsentRequestGrantScope' Lens
acceptOAuth2ConsentRequestGrantScopeL :: Lens_' AcceptOAuth2ConsentRequest (Maybe [Text])
acceptOAuth2ConsentRequestGrantScopeL f AcceptOAuth2ConsentRequest{..} = (\acceptOAuth2ConsentRequestGrantScope -> AcceptOAuth2ConsentRequest { acceptOAuth2ConsentRequestGrantScope, ..} ) <$> f acceptOAuth2ConsentRequestGrantScope
{-# INLINE acceptOAuth2ConsentRequestGrantScopeL #-}

-- | 'acceptOAuth2ConsentRequestHandledAt' Lens
acceptOAuth2ConsentRequestHandledAtL :: Lens_' AcceptOAuth2ConsentRequest (Maybe DateTime)
acceptOAuth2ConsentRequestHandledAtL f AcceptOAuth2ConsentRequest{..} = (\acceptOAuth2ConsentRequestHandledAt -> AcceptOAuth2ConsentRequest { acceptOAuth2ConsentRequestHandledAt, ..} ) <$> f acceptOAuth2ConsentRequestHandledAt
{-# INLINE acceptOAuth2ConsentRequestHandledAtL #-}

-- | 'acceptOAuth2ConsentRequestRemember' Lens
acceptOAuth2ConsentRequestRememberL :: Lens_' AcceptOAuth2ConsentRequest (Maybe Bool)
acceptOAuth2ConsentRequestRememberL f AcceptOAuth2ConsentRequest{..} = (\acceptOAuth2ConsentRequestRemember -> AcceptOAuth2ConsentRequest { acceptOAuth2ConsentRequestRemember, ..} ) <$> f acceptOAuth2ConsentRequestRemember
{-# INLINE acceptOAuth2ConsentRequestRememberL #-}

-- | 'acceptOAuth2ConsentRequestRememberFor' Lens
acceptOAuth2ConsentRequestRememberForL :: Lens_' AcceptOAuth2ConsentRequest (Maybe Integer)
acceptOAuth2ConsentRequestRememberForL f AcceptOAuth2ConsentRequest{..} = (\acceptOAuth2ConsentRequestRememberFor -> AcceptOAuth2ConsentRequest { acceptOAuth2ConsentRequestRememberFor, ..} ) <$> f acceptOAuth2ConsentRequestRememberFor
{-# INLINE acceptOAuth2ConsentRequestRememberForL #-}

-- | 'acceptOAuth2ConsentRequestSession' Lens
acceptOAuth2ConsentRequestSessionL :: Lens_' AcceptOAuth2ConsentRequest (Maybe AcceptOAuth2ConsentRequestSession)
acceptOAuth2ConsentRequestSessionL f AcceptOAuth2ConsentRequest{..} = (\acceptOAuth2ConsentRequestSession -> AcceptOAuth2ConsentRequest { acceptOAuth2ConsentRequestSession, ..} ) <$> f acceptOAuth2ConsentRequestSession
{-# INLINE acceptOAuth2ConsentRequestSessionL #-}



-- * AcceptOAuth2ConsentRequestSession

-- | 'acceptOAuth2ConsentRequestSessionAccessToken' Lens
acceptOAuth2ConsentRequestSessionAccessTokenL :: Lens_' AcceptOAuth2ConsentRequestSession (Maybe A.Value)
acceptOAuth2ConsentRequestSessionAccessTokenL f AcceptOAuth2ConsentRequestSession{..} = (\acceptOAuth2ConsentRequestSessionAccessToken -> AcceptOAuth2ConsentRequestSession { acceptOAuth2ConsentRequestSessionAccessToken, ..} ) <$> f acceptOAuth2ConsentRequestSessionAccessToken
{-# INLINE acceptOAuth2ConsentRequestSessionAccessTokenL #-}

-- | 'acceptOAuth2ConsentRequestSessionIdToken' Lens
acceptOAuth2ConsentRequestSessionIdTokenL :: Lens_' AcceptOAuth2ConsentRequestSession (Maybe A.Value)
acceptOAuth2ConsentRequestSessionIdTokenL f AcceptOAuth2ConsentRequestSession{..} = (\acceptOAuth2ConsentRequestSessionIdToken -> AcceptOAuth2ConsentRequestSession { acceptOAuth2ConsentRequestSessionIdToken, ..} ) <$> f acceptOAuth2ConsentRequestSessionIdToken
{-# INLINE acceptOAuth2ConsentRequestSessionIdTokenL #-}



-- * AcceptOAuth2LoginRequest

-- | 'acceptOAuth2LoginRequestAcr' Lens
acceptOAuth2LoginRequestAcrL :: Lens_' AcceptOAuth2LoginRequest (Maybe Text)
acceptOAuth2LoginRequestAcrL f AcceptOAuth2LoginRequest{..} = (\acceptOAuth2LoginRequestAcr -> AcceptOAuth2LoginRequest { acceptOAuth2LoginRequestAcr, ..} ) <$> f acceptOAuth2LoginRequestAcr
{-# INLINE acceptOAuth2LoginRequestAcrL #-}

-- | 'acceptOAuth2LoginRequestAmr' Lens
acceptOAuth2LoginRequestAmrL :: Lens_' AcceptOAuth2LoginRequest (Maybe [Text])
acceptOAuth2LoginRequestAmrL f AcceptOAuth2LoginRequest{..} = (\acceptOAuth2LoginRequestAmr -> AcceptOAuth2LoginRequest { acceptOAuth2LoginRequestAmr, ..} ) <$> f acceptOAuth2LoginRequestAmr
{-# INLINE acceptOAuth2LoginRequestAmrL #-}

-- | 'acceptOAuth2LoginRequestContext' Lens
acceptOAuth2LoginRequestContextL :: Lens_' AcceptOAuth2LoginRequest (Maybe A.Value)
acceptOAuth2LoginRequestContextL f AcceptOAuth2LoginRequest{..} = (\acceptOAuth2LoginRequestContext -> AcceptOAuth2LoginRequest { acceptOAuth2LoginRequestContext, ..} ) <$> f acceptOAuth2LoginRequestContext
{-# INLINE acceptOAuth2LoginRequestContextL #-}

-- | 'acceptOAuth2LoginRequestForceSubjectIdentifier' Lens
acceptOAuth2LoginRequestForceSubjectIdentifierL :: Lens_' AcceptOAuth2LoginRequest (Maybe Text)
acceptOAuth2LoginRequestForceSubjectIdentifierL f AcceptOAuth2LoginRequest{..} = (\acceptOAuth2LoginRequestForceSubjectIdentifier -> AcceptOAuth2LoginRequest { acceptOAuth2LoginRequestForceSubjectIdentifier, ..} ) <$> f acceptOAuth2LoginRequestForceSubjectIdentifier
{-# INLINE acceptOAuth2LoginRequestForceSubjectIdentifierL #-}

-- | 'acceptOAuth2LoginRequestRemember' Lens
acceptOAuth2LoginRequestRememberL :: Lens_' AcceptOAuth2LoginRequest (Maybe Bool)
acceptOAuth2LoginRequestRememberL f AcceptOAuth2LoginRequest{..} = (\acceptOAuth2LoginRequestRemember -> AcceptOAuth2LoginRequest { acceptOAuth2LoginRequestRemember, ..} ) <$> f acceptOAuth2LoginRequestRemember
{-# INLINE acceptOAuth2LoginRequestRememberL #-}

-- | 'acceptOAuth2LoginRequestRememberFor' Lens
acceptOAuth2LoginRequestRememberForL :: Lens_' AcceptOAuth2LoginRequest (Maybe Integer)
acceptOAuth2LoginRequestRememberForL f AcceptOAuth2LoginRequest{..} = (\acceptOAuth2LoginRequestRememberFor -> AcceptOAuth2LoginRequest { acceptOAuth2LoginRequestRememberFor, ..} ) <$> f acceptOAuth2LoginRequestRememberFor
{-# INLINE acceptOAuth2LoginRequestRememberForL #-}

-- | 'acceptOAuth2LoginRequestSubject' Lens
acceptOAuth2LoginRequestSubjectL :: Lens_' AcceptOAuth2LoginRequest (Text)
acceptOAuth2LoginRequestSubjectL f AcceptOAuth2LoginRequest{..} = (\acceptOAuth2LoginRequestSubject -> AcceptOAuth2LoginRequest { acceptOAuth2LoginRequestSubject, ..} ) <$> f acceptOAuth2LoginRequestSubject
{-# INLINE acceptOAuth2LoginRequestSubjectL #-}



-- * CreateJsonWebKeySet

-- | 'createJsonWebKeySetAlg' Lens
createJsonWebKeySetAlgL :: Lens_' CreateJsonWebKeySet (Text)
createJsonWebKeySetAlgL f CreateJsonWebKeySet{..} = (\createJsonWebKeySetAlg -> CreateJsonWebKeySet { createJsonWebKeySetAlg, ..} ) <$> f createJsonWebKeySetAlg
{-# INLINE createJsonWebKeySetAlgL #-}

-- | 'createJsonWebKeySetKid' Lens
createJsonWebKeySetKidL :: Lens_' CreateJsonWebKeySet (Text)
createJsonWebKeySetKidL f CreateJsonWebKeySet{..} = (\createJsonWebKeySetKid -> CreateJsonWebKeySet { createJsonWebKeySetKid, ..} ) <$> f createJsonWebKeySetKid
{-# INLINE createJsonWebKeySetKidL #-}

-- | 'createJsonWebKeySetUse' Lens
createJsonWebKeySetUseL :: Lens_' CreateJsonWebKeySet (Text)
createJsonWebKeySetUseL f CreateJsonWebKeySet{..} = (\createJsonWebKeySetUse -> CreateJsonWebKeySet { createJsonWebKeySetUse, ..} ) <$> f createJsonWebKeySetUse
{-# INLINE createJsonWebKeySetUseL #-}



-- * ErrorOAuth2

-- | 'errorOAuth2Error' Lens
errorOAuth2ErrorL :: Lens_' ErrorOAuth2 (Maybe Text)
errorOAuth2ErrorL f ErrorOAuth2{..} = (\errorOAuth2Error -> ErrorOAuth2 { errorOAuth2Error, ..} ) <$> f errorOAuth2Error
{-# INLINE errorOAuth2ErrorL #-}

-- | 'errorOAuth2ErrorDebug' Lens
errorOAuth2ErrorDebugL :: Lens_' ErrorOAuth2 (Maybe Text)
errorOAuth2ErrorDebugL f ErrorOAuth2{..} = (\errorOAuth2ErrorDebug -> ErrorOAuth2 { errorOAuth2ErrorDebug, ..} ) <$> f errorOAuth2ErrorDebug
{-# INLINE errorOAuth2ErrorDebugL #-}

-- | 'errorOAuth2ErrorDescription' Lens
errorOAuth2ErrorDescriptionL :: Lens_' ErrorOAuth2 (Maybe Text)
errorOAuth2ErrorDescriptionL f ErrorOAuth2{..} = (\errorOAuth2ErrorDescription -> ErrorOAuth2 { errorOAuth2ErrorDescription, ..} ) <$> f errorOAuth2ErrorDescription
{-# INLINE errorOAuth2ErrorDescriptionL #-}

-- | 'errorOAuth2ErrorHint' Lens
errorOAuth2ErrorHintL :: Lens_' ErrorOAuth2 (Maybe Text)
errorOAuth2ErrorHintL f ErrorOAuth2{..} = (\errorOAuth2ErrorHint -> ErrorOAuth2 { errorOAuth2ErrorHint, ..} ) <$> f errorOAuth2ErrorHint
{-# INLINE errorOAuth2ErrorHintL #-}

-- | 'errorOAuth2StatusCode' Lens
errorOAuth2StatusCodeL :: Lens_' ErrorOAuth2 (Maybe Integer)
errorOAuth2StatusCodeL f ErrorOAuth2{..} = (\errorOAuth2StatusCode -> ErrorOAuth2 { errorOAuth2StatusCode, ..} ) <$> f errorOAuth2StatusCode
{-# INLINE errorOAuth2StatusCodeL #-}



-- * GenericError

-- | 'genericErrorCode' Lens
genericErrorCodeL :: Lens_' GenericError (Maybe Integer)
genericErrorCodeL f GenericError{..} = (\genericErrorCode -> GenericError { genericErrorCode, ..} ) <$> f genericErrorCode
{-# INLINE genericErrorCodeL #-}

-- | 'genericErrorDebug' Lens
genericErrorDebugL :: Lens_' GenericError (Maybe Text)
genericErrorDebugL f GenericError{..} = (\genericErrorDebug -> GenericError { genericErrorDebug, ..} ) <$> f genericErrorDebug
{-# INLINE genericErrorDebugL #-}

-- | 'genericErrorDetails' Lens
genericErrorDetailsL :: Lens_' GenericError (Maybe A.Value)
genericErrorDetailsL f GenericError{..} = (\genericErrorDetails -> GenericError { genericErrorDetails, ..} ) <$> f genericErrorDetails
{-# INLINE genericErrorDetailsL #-}

-- | 'genericErrorId' Lens
genericErrorIdL :: Lens_' GenericError (Maybe Text)
genericErrorIdL f GenericError{..} = (\genericErrorId -> GenericError { genericErrorId, ..} ) <$> f genericErrorId
{-# INLINE genericErrorIdL #-}

-- | 'genericErrorMessage' Lens
genericErrorMessageL :: Lens_' GenericError (Text)
genericErrorMessageL f GenericError{..} = (\genericErrorMessage -> GenericError { genericErrorMessage, ..} ) <$> f genericErrorMessage
{-# INLINE genericErrorMessageL #-}

-- | 'genericErrorReason' Lens
genericErrorReasonL :: Lens_' GenericError (Maybe Text)
genericErrorReasonL f GenericError{..} = (\genericErrorReason -> GenericError { genericErrorReason, ..} ) <$> f genericErrorReason
{-# INLINE genericErrorReasonL #-}

-- | 'genericErrorRequest' Lens
genericErrorRequestL :: Lens_' GenericError (Maybe Text)
genericErrorRequestL f GenericError{..} = (\genericErrorRequest -> GenericError { genericErrorRequest, ..} ) <$> f genericErrorRequest
{-# INLINE genericErrorRequestL #-}

-- | 'genericErrorStatus' Lens
genericErrorStatusL :: Lens_' GenericError (Maybe Text)
genericErrorStatusL f GenericError{..} = (\genericErrorStatus -> GenericError { genericErrorStatus, ..} ) <$> f genericErrorStatus
{-# INLINE genericErrorStatusL #-}



-- * GetVersion200Response

-- | 'getVersion200ResponseVersion' Lens
getVersion200ResponseVersionL :: Lens_' GetVersion200Response (Maybe Text)
getVersion200ResponseVersionL f GetVersion200Response{..} = (\getVersion200ResponseVersion -> GetVersion200Response { getVersion200ResponseVersion, ..} ) <$> f getVersion200ResponseVersion
{-# INLINE getVersion200ResponseVersionL #-}



-- * HealthNotReadyStatus

-- | 'healthNotReadyStatusErrors' Lens
healthNotReadyStatusErrorsL :: Lens_' HealthNotReadyStatus (Maybe (Map.Map String Text))
healthNotReadyStatusErrorsL f HealthNotReadyStatus{..} = (\healthNotReadyStatusErrors -> HealthNotReadyStatus { healthNotReadyStatusErrors, ..} ) <$> f healthNotReadyStatusErrors
{-# INLINE healthNotReadyStatusErrorsL #-}



-- * HealthStatus

-- | 'healthStatusStatus' Lens
healthStatusStatusL :: Lens_' HealthStatus (Maybe Text)
healthStatusStatusL f HealthStatus{..} = (\healthStatusStatus -> HealthStatus { healthStatusStatus, ..} ) <$> f healthStatusStatus
{-# INLINE healthStatusStatusL #-}



-- * IntrospectedOAuth2Token

-- | 'introspectedOAuth2TokenActive' Lens
introspectedOAuth2TokenActiveL :: Lens_' IntrospectedOAuth2Token (Bool)
introspectedOAuth2TokenActiveL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenActive -> IntrospectedOAuth2Token { introspectedOAuth2TokenActive, ..} ) <$> f introspectedOAuth2TokenActive
{-# INLINE introspectedOAuth2TokenActiveL #-}

-- | 'introspectedOAuth2TokenAud' Lens
introspectedOAuth2TokenAudL :: Lens_' IntrospectedOAuth2Token (Maybe [Text])
introspectedOAuth2TokenAudL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenAud -> IntrospectedOAuth2Token { introspectedOAuth2TokenAud, ..} ) <$> f introspectedOAuth2TokenAud
{-# INLINE introspectedOAuth2TokenAudL #-}

-- | 'introspectedOAuth2TokenClientId' Lens
introspectedOAuth2TokenClientIdL :: Lens_' IntrospectedOAuth2Token (Maybe Text)
introspectedOAuth2TokenClientIdL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenClientId -> IntrospectedOAuth2Token { introspectedOAuth2TokenClientId, ..} ) <$> f introspectedOAuth2TokenClientId
{-# INLINE introspectedOAuth2TokenClientIdL #-}

-- | 'introspectedOAuth2TokenExp' Lens
introspectedOAuth2TokenExpL :: Lens_' IntrospectedOAuth2Token (Maybe Integer)
introspectedOAuth2TokenExpL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenExp -> IntrospectedOAuth2Token { introspectedOAuth2TokenExp, ..} ) <$> f introspectedOAuth2TokenExp
{-# INLINE introspectedOAuth2TokenExpL #-}

-- | 'introspectedOAuth2TokenExt' Lens
introspectedOAuth2TokenExtL :: Lens_' IntrospectedOAuth2Token (Maybe (Map.Map String A.Value))
introspectedOAuth2TokenExtL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenExt -> IntrospectedOAuth2Token { introspectedOAuth2TokenExt, ..} ) <$> f introspectedOAuth2TokenExt
{-# INLINE introspectedOAuth2TokenExtL #-}

-- | 'introspectedOAuth2TokenIat' Lens
introspectedOAuth2TokenIatL :: Lens_' IntrospectedOAuth2Token (Maybe Integer)
introspectedOAuth2TokenIatL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenIat -> IntrospectedOAuth2Token { introspectedOAuth2TokenIat, ..} ) <$> f introspectedOAuth2TokenIat
{-# INLINE introspectedOAuth2TokenIatL #-}

-- | 'introspectedOAuth2TokenIss' Lens
introspectedOAuth2TokenIssL :: Lens_' IntrospectedOAuth2Token (Maybe Text)
introspectedOAuth2TokenIssL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenIss -> IntrospectedOAuth2Token { introspectedOAuth2TokenIss, ..} ) <$> f introspectedOAuth2TokenIss
{-# INLINE introspectedOAuth2TokenIssL #-}

-- | 'introspectedOAuth2TokenNbf' Lens
introspectedOAuth2TokenNbfL :: Lens_' IntrospectedOAuth2Token (Maybe Integer)
introspectedOAuth2TokenNbfL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenNbf -> IntrospectedOAuth2Token { introspectedOAuth2TokenNbf, ..} ) <$> f introspectedOAuth2TokenNbf
{-# INLINE introspectedOAuth2TokenNbfL #-}

-- | 'introspectedOAuth2TokenObfuscatedSubject' Lens
introspectedOAuth2TokenObfuscatedSubjectL :: Lens_' IntrospectedOAuth2Token (Maybe Text)
introspectedOAuth2TokenObfuscatedSubjectL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenObfuscatedSubject -> IntrospectedOAuth2Token { introspectedOAuth2TokenObfuscatedSubject, ..} ) <$> f introspectedOAuth2TokenObfuscatedSubject
{-# INLINE introspectedOAuth2TokenObfuscatedSubjectL #-}

-- | 'introspectedOAuth2TokenScope' Lens
introspectedOAuth2TokenScopeL :: Lens_' IntrospectedOAuth2Token (Maybe Text)
introspectedOAuth2TokenScopeL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenScope -> IntrospectedOAuth2Token { introspectedOAuth2TokenScope, ..} ) <$> f introspectedOAuth2TokenScope
{-# INLINE introspectedOAuth2TokenScopeL #-}

-- | 'introspectedOAuth2TokenSub' Lens
introspectedOAuth2TokenSubL :: Lens_' IntrospectedOAuth2Token (Maybe Text)
introspectedOAuth2TokenSubL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenSub -> IntrospectedOAuth2Token { introspectedOAuth2TokenSub, ..} ) <$> f introspectedOAuth2TokenSub
{-# INLINE introspectedOAuth2TokenSubL #-}

-- | 'introspectedOAuth2TokenTokenType' Lens
introspectedOAuth2TokenTokenTypeL :: Lens_' IntrospectedOAuth2Token (Maybe Text)
introspectedOAuth2TokenTokenTypeL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenTokenType -> IntrospectedOAuth2Token { introspectedOAuth2TokenTokenType, ..} ) <$> f introspectedOAuth2TokenTokenType
{-# INLINE introspectedOAuth2TokenTokenTypeL #-}

-- | 'introspectedOAuth2TokenTokenUse' Lens
introspectedOAuth2TokenTokenUseL :: Lens_' IntrospectedOAuth2Token (Maybe Text)
introspectedOAuth2TokenTokenUseL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenTokenUse -> IntrospectedOAuth2Token { introspectedOAuth2TokenTokenUse, ..} ) <$> f introspectedOAuth2TokenTokenUse
{-# INLINE introspectedOAuth2TokenTokenUseL #-}

-- | 'introspectedOAuth2TokenUsername' Lens
introspectedOAuth2TokenUsernameL :: Lens_' IntrospectedOAuth2Token (Maybe Text)
introspectedOAuth2TokenUsernameL f IntrospectedOAuth2Token{..} = (\introspectedOAuth2TokenUsername -> IntrospectedOAuth2Token { introspectedOAuth2TokenUsername, ..} ) <$> f introspectedOAuth2TokenUsername
{-# INLINE introspectedOAuth2TokenUsernameL #-}



-- * IsReady200Response

-- | 'isReady200ResponseStatus' Lens
isReady200ResponseStatusL :: Lens_' IsReady200Response (Maybe Text)
isReady200ResponseStatusL f IsReady200Response{..} = (\isReady200ResponseStatus -> IsReady200Response { isReady200ResponseStatus, ..} ) <$> f isReady200ResponseStatus
{-# INLINE isReady200ResponseStatusL #-}



-- * IsReady503Response

-- | 'isReady503ResponseErrors' Lens
isReady503ResponseErrorsL :: Lens_' IsReady503Response (Maybe (Map.Map String Text))
isReady503ResponseErrorsL f IsReady503Response{..} = (\isReady503ResponseErrors -> IsReady503Response { isReady503ResponseErrors, ..} ) <$> f isReady503ResponseErrors
{-# INLINE isReady503ResponseErrorsL #-}



-- * JsonPatch

-- | 'jsonPatchFrom' Lens
jsonPatchFromL :: Lens_' JsonPatch (Maybe Text)
jsonPatchFromL f JsonPatch{..} = (\jsonPatchFrom -> JsonPatch { jsonPatchFrom, ..} ) <$> f jsonPatchFrom
{-# INLINE jsonPatchFromL #-}

-- | 'jsonPatchOp' Lens
jsonPatchOpL :: Lens_' JsonPatch (Text)
jsonPatchOpL f JsonPatch{..} = (\jsonPatchOp -> JsonPatch { jsonPatchOp, ..} ) <$> f jsonPatchOp
{-# INLINE jsonPatchOpL #-}

-- | 'jsonPatchPath' Lens
jsonPatchPathL :: Lens_' JsonPatch (Text)
jsonPatchPathL f JsonPatch{..} = (\jsonPatchPath -> JsonPatch { jsonPatchPath, ..} ) <$> f jsonPatchPath
{-# INLINE jsonPatchPathL #-}

-- | 'jsonPatchValue' Lens
jsonPatchValueL :: Lens_' JsonPatch (Maybe A.Value)
jsonPatchValueL f JsonPatch{..} = (\jsonPatchValue -> JsonPatch { jsonPatchValue, ..} ) <$> f jsonPatchValue
{-# INLINE jsonPatchValueL #-}



-- * JsonWebKey

-- | 'jsonWebKeyAlg' Lens
jsonWebKeyAlgL :: Lens_' JsonWebKey (Text)
jsonWebKeyAlgL f JsonWebKey{..} = (\jsonWebKeyAlg -> JsonWebKey { jsonWebKeyAlg, ..} ) <$> f jsonWebKeyAlg
{-# INLINE jsonWebKeyAlgL #-}

-- | 'jsonWebKeyCrv' Lens
jsonWebKeyCrvL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyCrvL f JsonWebKey{..} = (\jsonWebKeyCrv -> JsonWebKey { jsonWebKeyCrv, ..} ) <$> f jsonWebKeyCrv
{-# INLINE jsonWebKeyCrvL #-}

-- | 'jsonWebKeyD' Lens
jsonWebKeyDL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyDL f JsonWebKey{..} = (\jsonWebKeyD -> JsonWebKey { jsonWebKeyD, ..} ) <$> f jsonWebKeyD
{-# INLINE jsonWebKeyDL #-}

-- | 'jsonWebKeyDp' Lens
jsonWebKeyDpL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyDpL f JsonWebKey{..} = (\jsonWebKeyDp -> JsonWebKey { jsonWebKeyDp, ..} ) <$> f jsonWebKeyDp
{-# INLINE jsonWebKeyDpL #-}

-- | 'jsonWebKeyDq' Lens
jsonWebKeyDqL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyDqL f JsonWebKey{..} = (\jsonWebKeyDq -> JsonWebKey { jsonWebKeyDq, ..} ) <$> f jsonWebKeyDq
{-# INLINE jsonWebKeyDqL #-}

-- | 'jsonWebKeyE' Lens
jsonWebKeyEL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyEL f JsonWebKey{..} = (\jsonWebKeyE -> JsonWebKey { jsonWebKeyE, ..} ) <$> f jsonWebKeyE
{-# INLINE jsonWebKeyEL #-}

-- | 'jsonWebKeyK' Lens
jsonWebKeyKL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyKL f JsonWebKey{..} = (\jsonWebKeyK -> JsonWebKey { jsonWebKeyK, ..} ) <$> f jsonWebKeyK
{-# INLINE jsonWebKeyKL #-}

-- | 'jsonWebKeyKid' Lens
jsonWebKeyKidL :: Lens_' JsonWebKey (Text)
jsonWebKeyKidL f JsonWebKey{..} = (\jsonWebKeyKid -> JsonWebKey { jsonWebKeyKid, ..} ) <$> f jsonWebKeyKid
{-# INLINE jsonWebKeyKidL #-}

-- | 'jsonWebKeyKty' Lens
jsonWebKeyKtyL :: Lens_' JsonWebKey (Text)
jsonWebKeyKtyL f JsonWebKey{..} = (\jsonWebKeyKty -> JsonWebKey { jsonWebKeyKty, ..} ) <$> f jsonWebKeyKty
{-# INLINE jsonWebKeyKtyL #-}

-- | 'jsonWebKeyN' Lens
jsonWebKeyNL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyNL f JsonWebKey{..} = (\jsonWebKeyN -> JsonWebKey { jsonWebKeyN, ..} ) <$> f jsonWebKeyN
{-# INLINE jsonWebKeyNL #-}

-- | 'jsonWebKeyP' Lens
jsonWebKeyPL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyPL f JsonWebKey{..} = (\jsonWebKeyP -> JsonWebKey { jsonWebKeyP, ..} ) <$> f jsonWebKeyP
{-# INLINE jsonWebKeyPL #-}

-- | 'jsonWebKeyQ' Lens
jsonWebKeyQL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyQL f JsonWebKey{..} = (\jsonWebKeyQ -> JsonWebKey { jsonWebKeyQ, ..} ) <$> f jsonWebKeyQ
{-# INLINE jsonWebKeyQL #-}

-- | 'jsonWebKeyQi' Lens
jsonWebKeyQiL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyQiL f JsonWebKey{..} = (\jsonWebKeyQi -> JsonWebKey { jsonWebKeyQi, ..} ) <$> f jsonWebKeyQi
{-# INLINE jsonWebKeyQiL #-}

-- | 'jsonWebKeyUse' Lens
jsonWebKeyUseL :: Lens_' JsonWebKey (Text)
jsonWebKeyUseL f JsonWebKey{..} = (\jsonWebKeyUse -> JsonWebKey { jsonWebKeyUse, ..} ) <$> f jsonWebKeyUse
{-# INLINE jsonWebKeyUseL #-}

-- | 'jsonWebKeyX' Lens
jsonWebKeyXL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyXL f JsonWebKey{..} = (\jsonWebKeyX -> JsonWebKey { jsonWebKeyX, ..} ) <$> f jsonWebKeyX
{-# INLINE jsonWebKeyXL #-}

-- | 'jsonWebKeyX5c' Lens
jsonWebKeyX5cL :: Lens_' JsonWebKey (Maybe [Text])
jsonWebKeyX5cL f JsonWebKey{..} = (\jsonWebKeyX5c -> JsonWebKey { jsonWebKeyX5c, ..} ) <$> f jsonWebKeyX5c
{-# INLINE jsonWebKeyX5cL #-}

-- | 'jsonWebKeyY' Lens
jsonWebKeyYL :: Lens_' JsonWebKey (Maybe Text)
jsonWebKeyYL f JsonWebKey{..} = (\jsonWebKeyY -> JsonWebKey { jsonWebKeyY, ..} ) <$> f jsonWebKeyY
{-# INLINE jsonWebKeyYL #-}



-- * JsonWebKeySet

-- | 'jsonWebKeySetKeys' Lens
jsonWebKeySetKeysL :: Lens_' JsonWebKeySet (Maybe [JsonWebKey])
jsonWebKeySetKeysL f JsonWebKeySet{..} = (\jsonWebKeySetKeys -> JsonWebKeySet { jsonWebKeySetKeys, ..} ) <$> f jsonWebKeySetKeys
{-# INLINE jsonWebKeySetKeysL #-}



-- * OAuth2Client

-- | 'oAuth2ClientAllowedCorsOrigins' Lens
oAuth2ClientAllowedCorsOriginsL :: Lens_' OAuth2Client (Maybe [Text])
oAuth2ClientAllowedCorsOriginsL f OAuth2Client{..} = (\oAuth2ClientAllowedCorsOrigins -> OAuth2Client { oAuth2ClientAllowedCorsOrigins, ..} ) <$> f oAuth2ClientAllowedCorsOrigins
{-# INLINE oAuth2ClientAllowedCorsOriginsL #-}

-- | 'oAuth2ClientAudience' Lens
oAuth2ClientAudienceL :: Lens_' OAuth2Client (Maybe [Text])
oAuth2ClientAudienceL f OAuth2Client{..} = (\oAuth2ClientAudience -> OAuth2Client { oAuth2ClientAudience, ..} ) <$> f oAuth2ClientAudience
{-# INLINE oAuth2ClientAudienceL #-}

-- | 'oAuth2ClientAuthorizationCodeGrantAccessTokenLifespan' Lens
oAuth2ClientAuthorizationCodeGrantAccessTokenLifespanL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientAuthorizationCodeGrantAccessTokenLifespanL f OAuth2Client{..} = (\oAuth2ClientAuthorizationCodeGrantAccessTokenLifespan -> OAuth2Client { oAuth2ClientAuthorizationCodeGrantAccessTokenLifespan, ..} ) <$> f oAuth2ClientAuthorizationCodeGrantAccessTokenLifespan
{-# INLINE oAuth2ClientAuthorizationCodeGrantAccessTokenLifespanL #-}

-- | 'oAuth2ClientAuthorizationCodeGrantIdTokenLifespan' Lens
oAuth2ClientAuthorizationCodeGrantIdTokenLifespanL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientAuthorizationCodeGrantIdTokenLifespanL f OAuth2Client{..} = (\oAuth2ClientAuthorizationCodeGrantIdTokenLifespan -> OAuth2Client { oAuth2ClientAuthorizationCodeGrantIdTokenLifespan, ..} ) <$> f oAuth2ClientAuthorizationCodeGrantIdTokenLifespan
{-# INLINE oAuth2ClientAuthorizationCodeGrantIdTokenLifespanL #-}

-- | 'oAuth2ClientAuthorizationCodeGrantRefreshTokenLifespan' Lens
oAuth2ClientAuthorizationCodeGrantRefreshTokenLifespanL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientAuthorizationCodeGrantRefreshTokenLifespanL f OAuth2Client{..} = (\oAuth2ClientAuthorizationCodeGrantRefreshTokenLifespan -> OAuth2Client { oAuth2ClientAuthorizationCodeGrantRefreshTokenLifespan, ..} ) <$> f oAuth2ClientAuthorizationCodeGrantRefreshTokenLifespan
{-# INLINE oAuth2ClientAuthorizationCodeGrantRefreshTokenLifespanL #-}

-- | 'oAuth2ClientBackchannelLogoutSessionRequired' Lens
oAuth2ClientBackchannelLogoutSessionRequiredL :: Lens_' OAuth2Client (Maybe Bool)
oAuth2ClientBackchannelLogoutSessionRequiredL f OAuth2Client{..} = (\oAuth2ClientBackchannelLogoutSessionRequired -> OAuth2Client { oAuth2ClientBackchannelLogoutSessionRequired, ..} ) <$> f oAuth2ClientBackchannelLogoutSessionRequired
{-# INLINE oAuth2ClientBackchannelLogoutSessionRequiredL #-}

-- | 'oAuth2ClientBackchannelLogoutUri' Lens
oAuth2ClientBackchannelLogoutUriL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientBackchannelLogoutUriL f OAuth2Client{..} = (\oAuth2ClientBackchannelLogoutUri -> OAuth2Client { oAuth2ClientBackchannelLogoutUri, ..} ) <$> f oAuth2ClientBackchannelLogoutUri
{-# INLINE oAuth2ClientBackchannelLogoutUriL #-}

-- | 'oAuth2ClientClientCredentialsGrantAccessTokenLifespan' Lens
oAuth2ClientClientCredentialsGrantAccessTokenLifespanL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientClientCredentialsGrantAccessTokenLifespanL f OAuth2Client{..} = (\oAuth2ClientClientCredentialsGrantAccessTokenLifespan -> OAuth2Client { oAuth2ClientClientCredentialsGrantAccessTokenLifespan, ..} ) <$> f oAuth2ClientClientCredentialsGrantAccessTokenLifespan
{-# INLINE oAuth2ClientClientCredentialsGrantAccessTokenLifespanL #-}

-- | 'oAuth2ClientClientId' Lens
oAuth2ClientClientIdL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientClientIdL f OAuth2Client{..} = (\oAuth2ClientClientId -> OAuth2Client { oAuth2ClientClientId, ..} ) <$> f oAuth2ClientClientId
{-# INLINE oAuth2ClientClientIdL #-}

-- | 'oAuth2ClientClientName' Lens
oAuth2ClientClientNameL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientClientNameL f OAuth2Client{..} = (\oAuth2ClientClientName -> OAuth2Client { oAuth2ClientClientName, ..} ) <$> f oAuth2ClientClientName
{-# INLINE oAuth2ClientClientNameL #-}

-- | 'oAuth2ClientClientSecret' Lens
oAuth2ClientClientSecretL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientClientSecretL f OAuth2Client{..} = (\oAuth2ClientClientSecret -> OAuth2Client { oAuth2ClientClientSecret, ..} ) <$> f oAuth2ClientClientSecret
{-# INLINE oAuth2ClientClientSecretL #-}

-- | 'oAuth2ClientClientSecretExpiresAt' Lens
oAuth2ClientClientSecretExpiresAtL :: Lens_' OAuth2Client (Maybe Integer)
oAuth2ClientClientSecretExpiresAtL f OAuth2Client{..} = (\oAuth2ClientClientSecretExpiresAt -> OAuth2Client { oAuth2ClientClientSecretExpiresAt, ..} ) <$> f oAuth2ClientClientSecretExpiresAt
{-# INLINE oAuth2ClientClientSecretExpiresAtL #-}

-- | 'oAuth2ClientClientUri' Lens
oAuth2ClientClientUriL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientClientUriL f OAuth2Client{..} = (\oAuth2ClientClientUri -> OAuth2Client { oAuth2ClientClientUri, ..} ) <$> f oAuth2ClientClientUri
{-# INLINE oAuth2ClientClientUriL #-}

-- | 'oAuth2ClientContacts' Lens
oAuth2ClientContactsL :: Lens_' OAuth2Client (Maybe [Text])
oAuth2ClientContactsL f OAuth2Client{..} = (\oAuth2ClientContacts -> OAuth2Client { oAuth2ClientContacts, ..} ) <$> f oAuth2ClientContacts
{-# INLINE oAuth2ClientContactsL #-}

-- | 'oAuth2ClientCreatedAt' Lens
oAuth2ClientCreatedAtL :: Lens_' OAuth2Client (Maybe DateTime)
oAuth2ClientCreatedAtL f OAuth2Client{..} = (\oAuth2ClientCreatedAt -> OAuth2Client { oAuth2ClientCreatedAt, ..} ) <$> f oAuth2ClientCreatedAt
{-# INLINE oAuth2ClientCreatedAtL #-}

-- | 'oAuth2ClientFrontchannelLogoutSessionRequired' Lens
oAuth2ClientFrontchannelLogoutSessionRequiredL :: Lens_' OAuth2Client (Maybe Bool)
oAuth2ClientFrontchannelLogoutSessionRequiredL f OAuth2Client{..} = (\oAuth2ClientFrontchannelLogoutSessionRequired -> OAuth2Client { oAuth2ClientFrontchannelLogoutSessionRequired, ..} ) <$> f oAuth2ClientFrontchannelLogoutSessionRequired
{-# INLINE oAuth2ClientFrontchannelLogoutSessionRequiredL #-}

-- | 'oAuth2ClientFrontchannelLogoutUri' Lens
oAuth2ClientFrontchannelLogoutUriL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientFrontchannelLogoutUriL f OAuth2Client{..} = (\oAuth2ClientFrontchannelLogoutUri -> OAuth2Client { oAuth2ClientFrontchannelLogoutUri, ..} ) <$> f oAuth2ClientFrontchannelLogoutUri
{-# INLINE oAuth2ClientFrontchannelLogoutUriL #-}

-- | 'oAuth2ClientGrantTypes' Lens
oAuth2ClientGrantTypesL :: Lens_' OAuth2Client (Maybe [Text])
oAuth2ClientGrantTypesL f OAuth2Client{..} = (\oAuth2ClientGrantTypes -> OAuth2Client { oAuth2ClientGrantTypes, ..} ) <$> f oAuth2ClientGrantTypes
{-# INLINE oAuth2ClientGrantTypesL #-}

-- | 'oAuth2ClientImplicitGrantAccessTokenLifespan' Lens
oAuth2ClientImplicitGrantAccessTokenLifespanL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientImplicitGrantAccessTokenLifespanL f OAuth2Client{..} = (\oAuth2ClientImplicitGrantAccessTokenLifespan -> OAuth2Client { oAuth2ClientImplicitGrantAccessTokenLifespan, ..} ) <$> f oAuth2ClientImplicitGrantAccessTokenLifespan
{-# INLINE oAuth2ClientImplicitGrantAccessTokenLifespanL #-}

-- | 'oAuth2ClientImplicitGrantIdTokenLifespan' Lens
oAuth2ClientImplicitGrantIdTokenLifespanL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientImplicitGrantIdTokenLifespanL f OAuth2Client{..} = (\oAuth2ClientImplicitGrantIdTokenLifespan -> OAuth2Client { oAuth2ClientImplicitGrantIdTokenLifespan, ..} ) <$> f oAuth2ClientImplicitGrantIdTokenLifespan
{-# INLINE oAuth2ClientImplicitGrantIdTokenLifespanL #-}

-- | 'oAuth2ClientJwks' Lens
oAuth2ClientJwksL :: Lens_' OAuth2Client (Maybe A.Value)
oAuth2ClientJwksL f OAuth2Client{..} = (\oAuth2ClientJwks -> OAuth2Client { oAuth2ClientJwks, ..} ) <$> f oAuth2ClientJwks
{-# INLINE oAuth2ClientJwksL #-}

-- | 'oAuth2ClientJwksUri' Lens
oAuth2ClientJwksUriL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientJwksUriL f OAuth2Client{..} = (\oAuth2ClientJwksUri -> OAuth2Client { oAuth2ClientJwksUri, ..} ) <$> f oAuth2ClientJwksUri
{-# INLINE oAuth2ClientJwksUriL #-}

-- | 'oAuth2ClientJwtBearerGrantAccessTokenLifespan' Lens
oAuth2ClientJwtBearerGrantAccessTokenLifespanL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientJwtBearerGrantAccessTokenLifespanL f OAuth2Client{..} = (\oAuth2ClientJwtBearerGrantAccessTokenLifespan -> OAuth2Client { oAuth2ClientJwtBearerGrantAccessTokenLifespan, ..} ) <$> f oAuth2ClientJwtBearerGrantAccessTokenLifespan
{-# INLINE oAuth2ClientJwtBearerGrantAccessTokenLifespanL #-}

-- | 'oAuth2ClientLogoUri' Lens
oAuth2ClientLogoUriL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientLogoUriL f OAuth2Client{..} = (\oAuth2ClientLogoUri -> OAuth2Client { oAuth2ClientLogoUri, ..} ) <$> f oAuth2ClientLogoUri
{-# INLINE oAuth2ClientLogoUriL #-}

-- | 'oAuth2ClientMetadata' Lens
oAuth2ClientMetadataL :: Lens_' OAuth2Client (Maybe A.Value)
oAuth2ClientMetadataL f OAuth2Client{..} = (\oAuth2ClientMetadata -> OAuth2Client { oAuth2ClientMetadata, ..} ) <$> f oAuth2ClientMetadata
{-# INLINE oAuth2ClientMetadataL #-}

-- | 'oAuth2ClientOwner' Lens
oAuth2ClientOwnerL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientOwnerL f OAuth2Client{..} = (\oAuth2ClientOwner -> OAuth2Client { oAuth2ClientOwner, ..} ) <$> f oAuth2ClientOwner
{-# INLINE oAuth2ClientOwnerL #-}

-- | 'oAuth2ClientPolicyUri' Lens
oAuth2ClientPolicyUriL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientPolicyUriL f OAuth2Client{..} = (\oAuth2ClientPolicyUri -> OAuth2Client { oAuth2ClientPolicyUri, ..} ) <$> f oAuth2ClientPolicyUri
{-# INLINE oAuth2ClientPolicyUriL #-}

-- | 'oAuth2ClientPostLogoutRedirectUris' Lens
oAuth2ClientPostLogoutRedirectUrisL :: Lens_' OAuth2Client (Maybe [Text])
oAuth2ClientPostLogoutRedirectUrisL f OAuth2Client{..} = (\oAuth2ClientPostLogoutRedirectUris -> OAuth2Client { oAuth2ClientPostLogoutRedirectUris, ..} ) <$> f oAuth2ClientPostLogoutRedirectUris
{-# INLINE oAuth2ClientPostLogoutRedirectUrisL #-}

-- | 'oAuth2ClientRedirectUris' Lens
oAuth2ClientRedirectUrisL :: Lens_' OAuth2Client (Maybe [Text])
oAuth2ClientRedirectUrisL f OAuth2Client{..} = (\oAuth2ClientRedirectUris -> OAuth2Client { oAuth2ClientRedirectUris, ..} ) <$> f oAuth2ClientRedirectUris
{-# INLINE oAuth2ClientRedirectUrisL #-}

-- | 'oAuth2ClientRefreshTokenGrantAccessTokenLifespan' Lens
oAuth2ClientRefreshTokenGrantAccessTokenLifespanL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientRefreshTokenGrantAccessTokenLifespanL f OAuth2Client{..} = (\oAuth2ClientRefreshTokenGrantAccessTokenLifespan -> OAuth2Client { oAuth2ClientRefreshTokenGrantAccessTokenLifespan, ..} ) <$> f oAuth2ClientRefreshTokenGrantAccessTokenLifespan
{-# INLINE oAuth2ClientRefreshTokenGrantAccessTokenLifespanL #-}

-- | 'oAuth2ClientRefreshTokenGrantIdTokenLifespan' Lens
oAuth2ClientRefreshTokenGrantIdTokenLifespanL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientRefreshTokenGrantIdTokenLifespanL f OAuth2Client{..} = (\oAuth2ClientRefreshTokenGrantIdTokenLifespan -> OAuth2Client { oAuth2ClientRefreshTokenGrantIdTokenLifespan, ..} ) <$> f oAuth2ClientRefreshTokenGrantIdTokenLifespan
{-# INLINE oAuth2ClientRefreshTokenGrantIdTokenLifespanL #-}

-- | 'oAuth2ClientRefreshTokenGrantRefreshTokenLifespan' Lens
oAuth2ClientRefreshTokenGrantRefreshTokenLifespanL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientRefreshTokenGrantRefreshTokenLifespanL f OAuth2Client{..} = (\oAuth2ClientRefreshTokenGrantRefreshTokenLifespan -> OAuth2Client { oAuth2ClientRefreshTokenGrantRefreshTokenLifespan, ..} ) <$> f oAuth2ClientRefreshTokenGrantRefreshTokenLifespan
{-# INLINE oAuth2ClientRefreshTokenGrantRefreshTokenLifespanL #-}

-- | 'oAuth2ClientRegistrationAccessToken' Lens
oAuth2ClientRegistrationAccessTokenL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientRegistrationAccessTokenL f OAuth2Client{..} = (\oAuth2ClientRegistrationAccessToken -> OAuth2Client { oAuth2ClientRegistrationAccessToken, ..} ) <$> f oAuth2ClientRegistrationAccessToken
{-# INLINE oAuth2ClientRegistrationAccessTokenL #-}

-- | 'oAuth2ClientRegistrationClientUri' Lens
oAuth2ClientRegistrationClientUriL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientRegistrationClientUriL f OAuth2Client{..} = (\oAuth2ClientRegistrationClientUri -> OAuth2Client { oAuth2ClientRegistrationClientUri, ..} ) <$> f oAuth2ClientRegistrationClientUri
{-# INLINE oAuth2ClientRegistrationClientUriL #-}

-- | 'oAuth2ClientRequestObjectSigningAlg' Lens
oAuth2ClientRequestObjectSigningAlgL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientRequestObjectSigningAlgL f OAuth2Client{..} = (\oAuth2ClientRequestObjectSigningAlg -> OAuth2Client { oAuth2ClientRequestObjectSigningAlg, ..} ) <$> f oAuth2ClientRequestObjectSigningAlg
{-# INLINE oAuth2ClientRequestObjectSigningAlgL #-}

-- | 'oAuth2ClientRequestUris' Lens
oAuth2ClientRequestUrisL :: Lens_' OAuth2Client (Maybe [Text])
oAuth2ClientRequestUrisL f OAuth2Client{..} = (\oAuth2ClientRequestUris -> OAuth2Client { oAuth2ClientRequestUris, ..} ) <$> f oAuth2ClientRequestUris
{-# INLINE oAuth2ClientRequestUrisL #-}

-- | 'oAuth2ClientResponseTypes' Lens
oAuth2ClientResponseTypesL :: Lens_' OAuth2Client (Maybe [Text])
oAuth2ClientResponseTypesL f OAuth2Client{..} = (\oAuth2ClientResponseTypes -> OAuth2Client { oAuth2ClientResponseTypes, ..} ) <$> f oAuth2ClientResponseTypes
{-# INLINE oAuth2ClientResponseTypesL #-}

-- | 'oAuth2ClientScope' Lens
oAuth2ClientScopeL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientScopeL f OAuth2Client{..} = (\oAuth2ClientScope -> OAuth2Client { oAuth2ClientScope, ..} ) <$> f oAuth2ClientScope
{-# INLINE oAuth2ClientScopeL #-}

-- | 'oAuth2ClientSectorIdentifierUri' Lens
oAuth2ClientSectorIdentifierUriL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientSectorIdentifierUriL f OAuth2Client{..} = (\oAuth2ClientSectorIdentifierUri -> OAuth2Client { oAuth2ClientSectorIdentifierUri, ..} ) <$> f oAuth2ClientSectorIdentifierUri
{-# INLINE oAuth2ClientSectorIdentifierUriL #-}

-- | 'oAuth2ClientSubjectType' Lens
oAuth2ClientSubjectTypeL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientSubjectTypeL f OAuth2Client{..} = (\oAuth2ClientSubjectType -> OAuth2Client { oAuth2ClientSubjectType, ..} ) <$> f oAuth2ClientSubjectType
{-# INLINE oAuth2ClientSubjectTypeL #-}

-- | 'oAuth2ClientTokenEndpointAuthMethod' Lens
oAuth2ClientTokenEndpointAuthMethodL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientTokenEndpointAuthMethodL f OAuth2Client{..} = (\oAuth2ClientTokenEndpointAuthMethod -> OAuth2Client { oAuth2ClientTokenEndpointAuthMethod, ..} ) <$> f oAuth2ClientTokenEndpointAuthMethod
{-# INLINE oAuth2ClientTokenEndpointAuthMethodL #-}

-- | 'oAuth2ClientTokenEndpointAuthSigningAlg' Lens
oAuth2ClientTokenEndpointAuthSigningAlgL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientTokenEndpointAuthSigningAlgL f OAuth2Client{..} = (\oAuth2ClientTokenEndpointAuthSigningAlg -> OAuth2Client { oAuth2ClientTokenEndpointAuthSigningAlg, ..} ) <$> f oAuth2ClientTokenEndpointAuthSigningAlg
{-# INLINE oAuth2ClientTokenEndpointAuthSigningAlgL #-}

-- | 'oAuth2ClientTosUri' Lens
oAuth2ClientTosUriL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientTosUriL f OAuth2Client{..} = (\oAuth2ClientTosUri -> OAuth2Client { oAuth2ClientTosUri, ..} ) <$> f oAuth2ClientTosUri
{-# INLINE oAuth2ClientTosUriL #-}

-- | 'oAuth2ClientUpdatedAt' Lens
oAuth2ClientUpdatedAtL :: Lens_' OAuth2Client (Maybe DateTime)
oAuth2ClientUpdatedAtL f OAuth2Client{..} = (\oAuth2ClientUpdatedAt -> OAuth2Client { oAuth2ClientUpdatedAt, ..} ) <$> f oAuth2ClientUpdatedAt
{-# INLINE oAuth2ClientUpdatedAtL #-}

-- | 'oAuth2ClientUserinfoSignedResponseAlg' Lens
oAuth2ClientUserinfoSignedResponseAlgL :: Lens_' OAuth2Client (Maybe Text)
oAuth2ClientUserinfoSignedResponseAlgL f OAuth2Client{..} = (\oAuth2ClientUserinfoSignedResponseAlg -> OAuth2Client { oAuth2ClientUserinfoSignedResponseAlg, ..} ) <$> f oAuth2ClientUserinfoSignedResponseAlg
{-# INLINE oAuth2ClientUserinfoSignedResponseAlgL #-}



-- * OAuth2ClientTokenLifespans

-- | 'oAuth2ClientTokenLifespansAuthorizationCodeGrantAccessTokenLifespan' Lens
oAuth2ClientTokenLifespansAuthorizationCodeGrantAccessTokenLifespanL :: Lens_' OAuth2ClientTokenLifespans (Maybe Text)
oAuth2ClientTokenLifespansAuthorizationCodeGrantAccessTokenLifespanL f OAuth2ClientTokenLifespans{..} = (\oAuth2ClientTokenLifespansAuthorizationCodeGrantAccessTokenLifespan -> OAuth2ClientTokenLifespans { oAuth2ClientTokenLifespansAuthorizationCodeGrantAccessTokenLifespan, ..} ) <$> f oAuth2ClientTokenLifespansAuthorizationCodeGrantAccessTokenLifespan
{-# INLINE oAuth2ClientTokenLifespansAuthorizationCodeGrantAccessTokenLifespanL #-}

-- | 'oAuth2ClientTokenLifespansAuthorizationCodeGrantIdTokenLifespan' Lens
oAuth2ClientTokenLifespansAuthorizationCodeGrantIdTokenLifespanL :: Lens_' OAuth2ClientTokenLifespans (Maybe Text)
oAuth2ClientTokenLifespansAuthorizationCodeGrantIdTokenLifespanL f OAuth2ClientTokenLifespans{..} = (\oAuth2ClientTokenLifespansAuthorizationCodeGrantIdTokenLifespan -> OAuth2ClientTokenLifespans { oAuth2ClientTokenLifespansAuthorizationCodeGrantIdTokenLifespan, ..} ) <$> f oAuth2ClientTokenLifespansAuthorizationCodeGrantIdTokenLifespan
{-# INLINE oAuth2ClientTokenLifespansAuthorizationCodeGrantIdTokenLifespanL #-}

-- | 'oAuth2ClientTokenLifespansAuthorizationCodeGrantRefreshTokenLifespan' Lens
oAuth2ClientTokenLifespansAuthorizationCodeGrantRefreshTokenLifespanL :: Lens_' OAuth2ClientTokenLifespans (Maybe Text)
oAuth2ClientTokenLifespansAuthorizationCodeGrantRefreshTokenLifespanL f OAuth2ClientTokenLifespans{..} = (\oAuth2ClientTokenLifespansAuthorizationCodeGrantRefreshTokenLifespan -> OAuth2ClientTokenLifespans { oAuth2ClientTokenLifespansAuthorizationCodeGrantRefreshTokenLifespan, ..} ) <$> f oAuth2ClientTokenLifespansAuthorizationCodeGrantRefreshTokenLifespan
{-# INLINE oAuth2ClientTokenLifespansAuthorizationCodeGrantRefreshTokenLifespanL #-}

-- | 'oAuth2ClientTokenLifespansClientCredentialsGrantAccessTokenLifespan' Lens
oAuth2ClientTokenLifespansClientCredentialsGrantAccessTokenLifespanL :: Lens_' OAuth2ClientTokenLifespans (Maybe Text)
oAuth2ClientTokenLifespansClientCredentialsGrantAccessTokenLifespanL f OAuth2ClientTokenLifespans{..} = (\oAuth2ClientTokenLifespansClientCredentialsGrantAccessTokenLifespan -> OAuth2ClientTokenLifespans { oAuth2ClientTokenLifespansClientCredentialsGrantAccessTokenLifespan, ..} ) <$> f oAuth2ClientTokenLifespansClientCredentialsGrantAccessTokenLifespan
{-# INLINE oAuth2ClientTokenLifespansClientCredentialsGrantAccessTokenLifespanL #-}

-- | 'oAuth2ClientTokenLifespansImplicitGrantAccessTokenLifespan' Lens
oAuth2ClientTokenLifespansImplicitGrantAccessTokenLifespanL :: Lens_' OAuth2ClientTokenLifespans (Maybe Text)
oAuth2ClientTokenLifespansImplicitGrantAccessTokenLifespanL f OAuth2ClientTokenLifespans{..} = (\oAuth2ClientTokenLifespansImplicitGrantAccessTokenLifespan -> OAuth2ClientTokenLifespans { oAuth2ClientTokenLifespansImplicitGrantAccessTokenLifespan, ..} ) <$> f oAuth2ClientTokenLifespansImplicitGrantAccessTokenLifespan
{-# INLINE oAuth2ClientTokenLifespansImplicitGrantAccessTokenLifespanL #-}

-- | 'oAuth2ClientTokenLifespansImplicitGrantIdTokenLifespan' Lens
oAuth2ClientTokenLifespansImplicitGrantIdTokenLifespanL :: Lens_' OAuth2ClientTokenLifespans (Maybe Text)
oAuth2ClientTokenLifespansImplicitGrantIdTokenLifespanL f OAuth2ClientTokenLifespans{..} = (\oAuth2ClientTokenLifespansImplicitGrantIdTokenLifespan -> OAuth2ClientTokenLifespans { oAuth2ClientTokenLifespansImplicitGrantIdTokenLifespan, ..} ) <$> f oAuth2ClientTokenLifespansImplicitGrantIdTokenLifespan
{-# INLINE oAuth2ClientTokenLifespansImplicitGrantIdTokenLifespanL #-}

-- | 'oAuth2ClientTokenLifespansJwtBearerGrantAccessTokenLifespan' Lens
oAuth2ClientTokenLifespansJwtBearerGrantAccessTokenLifespanL :: Lens_' OAuth2ClientTokenLifespans (Maybe Text)
oAuth2ClientTokenLifespansJwtBearerGrantAccessTokenLifespanL f OAuth2ClientTokenLifespans{..} = (\oAuth2ClientTokenLifespansJwtBearerGrantAccessTokenLifespan -> OAuth2ClientTokenLifespans { oAuth2ClientTokenLifespansJwtBearerGrantAccessTokenLifespan, ..} ) <$> f oAuth2ClientTokenLifespansJwtBearerGrantAccessTokenLifespan
{-# INLINE oAuth2ClientTokenLifespansJwtBearerGrantAccessTokenLifespanL #-}

-- | 'oAuth2ClientTokenLifespansRefreshTokenGrantAccessTokenLifespan' Lens
oAuth2ClientTokenLifespansRefreshTokenGrantAccessTokenLifespanL :: Lens_' OAuth2ClientTokenLifespans (Maybe Text)
oAuth2ClientTokenLifespansRefreshTokenGrantAccessTokenLifespanL f OAuth2ClientTokenLifespans{..} = (\oAuth2ClientTokenLifespansRefreshTokenGrantAccessTokenLifespan -> OAuth2ClientTokenLifespans { oAuth2ClientTokenLifespansRefreshTokenGrantAccessTokenLifespan, ..} ) <$> f oAuth2ClientTokenLifespansRefreshTokenGrantAccessTokenLifespan
{-# INLINE oAuth2ClientTokenLifespansRefreshTokenGrantAccessTokenLifespanL #-}

-- | 'oAuth2ClientTokenLifespansRefreshTokenGrantIdTokenLifespan' Lens
oAuth2ClientTokenLifespansRefreshTokenGrantIdTokenLifespanL :: Lens_' OAuth2ClientTokenLifespans (Maybe Text)
oAuth2ClientTokenLifespansRefreshTokenGrantIdTokenLifespanL f OAuth2ClientTokenLifespans{..} = (\oAuth2ClientTokenLifespansRefreshTokenGrantIdTokenLifespan -> OAuth2ClientTokenLifespans { oAuth2ClientTokenLifespansRefreshTokenGrantIdTokenLifespan, ..} ) <$> f oAuth2ClientTokenLifespansRefreshTokenGrantIdTokenLifespan
{-# INLINE oAuth2ClientTokenLifespansRefreshTokenGrantIdTokenLifespanL #-}

-- | 'oAuth2ClientTokenLifespansRefreshTokenGrantRefreshTokenLifespan' Lens
oAuth2ClientTokenLifespansRefreshTokenGrantRefreshTokenLifespanL :: Lens_' OAuth2ClientTokenLifespans (Maybe Text)
oAuth2ClientTokenLifespansRefreshTokenGrantRefreshTokenLifespanL f OAuth2ClientTokenLifespans{..} = (\oAuth2ClientTokenLifespansRefreshTokenGrantRefreshTokenLifespan -> OAuth2ClientTokenLifespans { oAuth2ClientTokenLifespansRefreshTokenGrantRefreshTokenLifespan, ..} ) <$> f oAuth2ClientTokenLifespansRefreshTokenGrantRefreshTokenLifespan
{-# INLINE oAuth2ClientTokenLifespansRefreshTokenGrantRefreshTokenLifespanL #-}



-- * OAuth2ConsentRequest

-- | 'oAuth2ConsentRequestAcr' Lens
oAuth2ConsentRequestAcrL :: Lens_' OAuth2ConsentRequest (Maybe Text)
oAuth2ConsentRequestAcrL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestAcr -> OAuth2ConsentRequest { oAuth2ConsentRequestAcr, ..} ) <$> f oAuth2ConsentRequestAcr
{-# INLINE oAuth2ConsentRequestAcrL #-}

-- | 'oAuth2ConsentRequestAmr' Lens
oAuth2ConsentRequestAmrL :: Lens_' OAuth2ConsentRequest (Maybe [Text])
oAuth2ConsentRequestAmrL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestAmr -> OAuth2ConsentRequest { oAuth2ConsentRequestAmr, ..} ) <$> f oAuth2ConsentRequestAmr
{-# INLINE oAuth2ConsentRequestAmrL #-}

-- | 'oAuth2ConsentRequestChallenge' Lens
oAuth2ConsentRequestChallengeL :: Lens_' OAuth2ConsentRequest (Text)
oAuth2ConsentRequestChallengeL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestChallenge -> OAuth2ConsentRequest { oAuth2ConsentRequestChallenge, ..} ) <$> f oAuth2ConsentRequestChallenge
{-# INLINE oAuth2ConsentRequestChallengeL #-}

-- | 'oAuth2ConsentRequestClient' Lens
oAuth2ConsentRequestClientL :: Lens_' OAuth2ConsentRequest (Maybe OAuth2Client)
oAuth2ConsentRequestClientL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestClient -> OAuth2ConsentRequest { oAuth2ConsentRequestClient, ..} ) <$> f oAuth2ConsentRequestClient
{-# INLINE oAuth2ConsentRequestClientL #-}

-- | 'oAuth2ConsentRequestContext' Lens
oAuth2ConsentRequestContextL :: Lens_' OAuth2ConsentRequest (Maybe A.Value)
oAuth2ConsentRequestContextL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestContext -> OAuth2ConsentRequest { oAuth2ConsentRequestContext, ..} ) <$> f oAuth2ConsentRequestContext
{-# INLINE oAuth2ConsentRequestContextL #-}

-- | 'oAuth2ConsentRequestLoginChallenge' Lens
oAuth2ConsentRequestLoginChallengeL :: Lens_' OAuth2ConsentRequest (Maybe Text)
oAuth2ConsentRequestLoginChallengeL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestLoginChallenge -> OAuth2ConsentRequest { oAuth2ConsentRequestLoginChallenge, ..} ) <$> f oAuth2ConsentRequestLoginChallenge
{-# INLINE oAuth2ConsentRequestLoginChallengeL #-}

-- | 'oAuth2ConsentRequestLoginSessionId' Lens
oAuth2ConsentRequestLoginSessionIdL :: Lens_' OAuth2ConsentRequest (Maybe Text)
oAuth2ConsentRequestLoginSessionIdL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestLoginSessionId -> OAuth2ConsentRequest { oAuth2ConsentRequestLoginSessionId, ..} ) <$> f oAuth2ConsentRequestLoginSessionId
{-# INLINE oAuth2ConsentRequestLoginSessionIdL #-}

-- | 'oAuth2ConsentRequestOidcContext' Lens
oAuth2ConsentRequestOidcContextL :: Lens_' OAuth2ConsentRequest (Maybe OAuth2ConsentRequestOpenIDConnectContext)
oAuth2ConsentRequestOidcContextL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestOidcContext -> OAuth2ConsentRequest { oAuth2ConsentRequestOidcContext, ..} ) <$> f oAuth2ConsentRequestOidcContext
{-# INLINE oAuth2ConsentRequestOidcContextL #-}

-- | 'oAuth2ConsentRequestRequestUrl' Lens
oAuth2ConsentRequestRequestUrlL :: Lens_' OAuth2ConsentRequest (Maybe Text)
oAuth2ConsentRequestRequestUrlL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestRequestUrl -> OAuth2ConsentRequest { oAuth2ConsentRequestRequestUrl, ..} ) <$> f oAuth2ConsentRequestRequestUrl
{-# INLINE oAuth2ConsentRequestRequestUrlL #-}

-- | 'oAuth2ConsentRequestRequestedAccessTokenAudience' Lens
oAuth2ConsentRequestRequestedAccessTokenAudienceL :: Lens_' OAuth2ConsentRequest (Maybe [Text])
oAuth2ConsentRequestRequestedAccessTokenAudienceL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestRequestedAccessTokenAudience -> OAuth2ConsentRequest { oAuth2ConsentRequestRequestedAccessTokenAudience, ..} ) <$> f oAuth2ConsentRequestRequestedAccessTokenAudience
{-# INLINE oAuth2ConsentRequestRequestedAccessTokenAudienceL #-}

-- | 'oAuth2ConsentRequestRequestedScope' Lens
oAuth2ConsentRequestRequestedScopeL :: Lens_' OAuth2ConsentRequest (Maybe [Text])
oAuth2ConsentRequestRequestedScopeL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestRequestedScope -> OAuth2ConsentRequest { oAuth2ConsentRequestRequestedScope, ..} ) <$> f oAuth2ConsentRequestRequestedScope
{-# INLINE oAuth2ConsentRequestRequestedScopeL #-}

-- | 'oAuth2ConsentRequestSkip' Lens
oAuth2ConsentRequestSkipL :: Lens_' OAuth2ConsentRequest (Maybe Bool)
oAuth2ConsentRequestSkipL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestSkip -> OAuth2ConsentRequest { oAuth2ConsentRequestSkip, ..} ) <$> f oAuth2ConsentRequestSkip
{-# INLINE oAuth2ConsentRequestSkipL #-}

-- | 'oAuth2ConsentRequestSubject' Lens
oAuth2ConsentRequestSubjectL :: Lens_' OAuth2ConsentRequest (Maybe Text)
oAuth2ConsentRequestSubjectL f OAuth2ConsentRequest{..} = (\oAuth2ConsentRequestSubject -> OAuth2ConsentRequest { oAuth2ConsentRequestSubject, ..} ) <$> f oAuth2ConsentRequestSubject
{-# INLINE oAuth2ConsentRequestSubjectL #-}



-- * OAuth2ConsentRequestOpenIDConnectContext

-- | 'oAuth2ConsentRequestOpenIDConnectContextAcrValues' Lens
oAuth2ConsentRequestOpenIDConnectContextAcrValuesL :: Lens_' OAuth2ConsentRequestOpenIDConnectContext (Maybe [Text])
oAuth2ConsentRequestOpenIDConnectContextAcrValuesL f OAuth2ConsentRequestOpenIDConnectContext{..} = (\oAuth2ConsentRequestOpenIDConnectContextAcrValues -> OAuth2ConsentRequestOpenIDConnectContext { oAuth2ConsentRequestOpenIDConnectContextAcrValues, ..} ) <$> f oAuth2ConsentRequestOpenIDConnectContextAcrValues
{-# INLINE oAuth2ConsentRequestOpenIDConnectContextAcrValuesL #-}

-- | 'oAuth2ConsentRequestOpenIDConnectContextDisplay' Lens
oAuth2ConsentRequestOpenIDConnectContextDisplayL :: Lens_' OAuth2ConsentRequestOpenIDConnectContext (Maybe Text)
oAuth2ConsentRequestOpenIDConnectContextDisplayL f OAuth2ConsentRequestOpenIDConnectContext{..} = (\oAuth2ConsentRequestOpenIDConnectContextDisplay -> OAuth2ConsentRequestOpenIDConnectContext { oAuth2ConsentRequestOpenIDConnectContextDisplay, ..} ) <$> f oAuth2ConsentRequestOpenIDConnectContextDisplay
{-# INLINE oAuth2ConsentRequestOpenIDConnectContextDisplayL #-}

-- | 'oAuth2ConsentRequestOpenIDConnectContextIdTokenHintClaims' Lens
oAuth2ConsentRequestOpenIDConnectContextIdTokenHintClaimsL :: Lens_' OAuth2ConsentRequestOpenIDConnectContext (Maybe (Map.Map String A.Value))
oAuth2ConsentRequestOpenIDConnectContextIdTokenHintClaimsL f OAuth2ConsentRequestOpenIDConnectContext{..} = (\oAuth2ConsentRequestOpenIDConnectContextIdTokenHintClaims -> OAuth2ConsentRequestOpenIDConnectContext { oAuth2ConsentRequestOpenIDConnectContextIdTokenHintClaims, ..} ) <$> f oAuth2ConsentRequestOpenIDConnectContextIdTokenHintClaims
{-# INLINE oAuth2ConsentRequestOpenIDConnectContextIdTokenHintClaimsL #-}

-- | 'oAuth2ConsentRequestOpenIDConnectContextLoginHint' Lens
oAuth2ConsentRequestOpenIDConnectContextLoginHintL :: Lens_' OAuth2ConsentRequestOpenIDConnectContext (Maybe Text)
oAuth2ConsentRequestOpenIDConnectContextLoginHintL f OAuth2ConsentRequestOpenIDConnectContext{..} = (\oAuth2ConsentRequestOpenIDConnectContextLoginHint -> OAuth2ConsentRequestOpenIDConnectContext { oAuth2ConsentRequestOpenIDConnectContextLoginHint, ..} ) <$> f oAuth2ConsentRequestOpenIDConnectContextLoginHint
{-# INLINE oAuth2ConsentRequestOpenIDConnectContextLoginHintL #-}

-- | 'oAuth2ConsentRequestOpenIDConnectContextUiLocales' Lens
oAuth2ConsentRequestOpenIDConnectContextUiLocalesL :: Lens_' OAuth2ConsentRequestOpenIDConnectContext (Maybe [Text])
oAuth2ConsentRequestOpenIDConnectContextUiLocalesL f OAuth2ConsentRequestOpenIDConnectContext{..} = (\oAuth2ConsentRequestOpenIDConnectContextUiLocales -> OAuth2ConsentRequestOpenIDConnectContext { oAuth2ConsentRequestOpenIDConnectContextUiLocales, ..} ) <$> f oAuth2ConsentRequestOpenIDConnectContextUiLocales
{-# INLINE oAuth2ConsentRequestOpenIDConnectContextUiLocalesL #-}



-- * OAuth2ConsentSession

-- | 'oAuth2ConsentSessionConsentRequest' Lens
oAuth2ConsentSessionConsentRequestL :: Lens_' OAuth2ConsentSession (Maybe OAuth2ConsentRequest)
oAuth2ConsentSessionConsentRequestL f OAuth2ConsentSession{..} = (\oAuth2ConsentSessionConsentRequest -> OAuth2ConsentSession { oAuth2ConsentSessionConsentRequest, ..} ) <$> f oAuth2ConsentSessionConsentRequest
{-# INLINE oAuth2ConsentSessionConsentRequestL #-}

-- | 'oAuth2ConsentSessionExpiresAt' Lens
oAuth2ConsentSessionExpiresAtL :: Lens_' OAuth2ConsentSession (Maybe OAuth2ConsentSessionExpiresAt)
oAuth2ConsentSessionExpiresAtL f OAuth2ConsentSession{..} = (\oAuth2ConsentSessionExpiresAt -> OAuth2ConsentSession { oAuth2ConsentSessionExpiresAt, ..} ) <$> f oAuth2ConsentSessionExpiresAt
{-# INLINE oAuth2ConsentSessionExpiresAtL #-}

-- | 'oAuth2ConsentSessionGrantAccessTokenAudience' Lens
oAuth2ConsentSessionGrantAccessTokenAudienceL :: Lens_' OAuth2ConsentSession (Maybe [Text])
oAuth2ConsentSessionGrantAccessTokenAudienceL f OAuth2ConsentSession{..} = (\oAuth2ConsentSessionGrantAccessTokenAudience -> OAuth2ConsentSession { oAuth2ConsentSessionGrantAccessTokenAudience, ..} ) <$> f oAuth2ConsentSessionGrantAccessTokenAudience
{-# INLINE oAuth2ConsentSessionGrantAccessTokenAudienceL #-}

-- | 'oAuth2ConsentSessionGrantScope' Lens
oAuth2ConsentSessionGrantScopeL :: Lens_' OAuth2ConsentSession (Maybe [Text])
oAuth2ConsentSessionGrantScopeL f OAuth2ConsentSession{..} = (\oAuth2ConsentSessionGrantScope -> OAuth2ConsentSession { oAuth2ConsentSessionGrantScope, ..} ) <$> f oAuth2ConsentSessionGrantScope
{-# INLINE oAuth2ConsentSessionGrantScopeL #-}

-- | 'oAuth2ConsentSessionHandledAt' Lens
oAuth2ConsentSessionHandledAtL :: Lens_' OAuth2ConsentSession (Maybe DateTime)
oAuth2ConsentSessionHandledAtL f OAuth2ConsentSession{..} = (\oAuth2ConsentSessionHandledAt -> OAuth2ConsentSession { oAuth2ConsentSessionHandledAt, ..} ) <$> f oAuth2ConsentSessionHandledAt
{-# INLINE oAuth2ConsentSessionHandledAtL #-}

-- | 'oAuth2ConsentSessionRemember' Lens
oAuth2ConsentSessionRememberL :: Lens_' OAuth2ConsentSession (Maybe Bool)
oAuth2ConsentSessionRememberL f OAuth2ConsentSession{..} = (\oAuth2ConsentSessionRemember -> OAuth2ConsentSession { oAuth2ConsentSessionRemember, ..} ) <$> f oAuth2ConsentSessionRemember
{-# INLINE oAuth2ConsentSessionRememberL #-}

-- | 'oAuth2ConsentSessionRememberFor' Lens
oAuth2ConsentSessionRememberForL :: Lens_' OAuth2ConsentSession (Maybe Integer)
oAuth2ConsentSessionRememberForL f OAuth2ConsentSession{..} = (\oAuth2ConsentSessionRememberFor -> OAuth2ConsentSession { oAuth2ConsentSessionRememberFor, ..} ) <$> f oAuth2ConsentSessionRememberFor
{-# INLINE oAuth2ConsentSessionRememberForL #-}

-- | 'oAuth2ConsentSessionSession' Lens
oAuth2ConsentSessionSessionL :: Lens_' OAuth2ConsentSession (Maybe AcceptOAuth2ConsentRequestSession)
oAuth2ConsentSessionSessionL f OAuth2ConsentSession{..} = (\oAuth2ConsentSessionSession -> OAuth2ConsentSession { oAuth2ConsentSessionSession, ..} ) <$> f oAuth2ConsentSessionSession
{-# INLINE oAuth2ConsentSessionSessionL #-}



-- * OAuth2ConsentSessionExpiresAt

-- | 'oAuth2ConsentSessionExpiresAtAccessToken' Lens
oAuth2ConsentSessionExpiresAtAccessTokenL :: Lens_' OAuth2ConsentSessionExpiresAt (Maybe DateTime)
oAuth2ConsentSessionExpiresAtAccessTokenL f OAuth2ConsentSessionExpiresAt{..} = (\oAuth2ConsentSessionExpiresAtAccessToken -> OAuth2ConsentSessionExpiresAt { oAuth2ConsentSessionExpiresAtAccessToken, ..} ) <$> f oAuth2ConsentSessionExpiresAtAccessToken
{-# INLINE oAuth2ConsentSessionExpiresAtAccessTokenL #-}

-- | 'oAuth2ConsentSessionExpiresAtAuthorizeCode' Lens
oAuth2ConsentSessionExpiresAtAuthorizeCodeL :: Lens_' OAuth2ConsentSessionExpiresAt (Maybe DateTime)
oAuth2ConsentSessionExpiresAtAuthorizeCodeL f OAuth2ConsentSessionExpiresAt{..} = (\oAuth2ConsentSessionExpiresAtAuthorizeCode -> OAuth2ConsentSessionExpiresAt { oAuth2ConsentSessionExpiresAtAuthorizeCode, ..} ) <$> f oAuth2ConsentSessionExpiresAtAuthorizeCode
{-# INLINE oAuth2ConsentSessionExpiresAtAuthorizeCodeL #-}

-- | 'oAuth2ConsentSessionExpiresAtIdToken' Lens
oAuth2ConsentSessionExpiresAtIdTokenL :: Lens_' OAuth2ConsentSessionExpiresAt (Maybe DateTime)
oAuth2ConsentSessionExpiresAtIdTokenL f OAuth2ConsentSessionExpiresAt{..} = (\oAuth2ConsentSessionExpiresAtIdToken -> OAuth2ConsentSessionExpiresAt { oAuth2ConsentSessionExpiresAtIdToken, ..} ) <$> f oAuth2ConsentSessionExpiresAtIdToken
{-# INLINE oAuth2ConsentSessionExpiresAtIdTokenL #-}

-- | 'oAuth2ConsentSessionExpiresAtParContext' Lens
oAuth2ConsentSessionExpiresAtParContextL :: Lens_' OAuth2ConsentSessionExpiresAt (Maybe DateTime)
oAuth2ConsentSessionExpiresAtParContextL f OAuth2ConsentSessionExpiresAt{..} = (\oAuth2ConsentSessionExpiresAtParContext -> OAuth2ConsentSessionExpiresAt { oAuth2ConsentSessionExpiresAtParContext, ..} ) <$> f oAuth2ConsentSessionExpiresAtParContext
{-# INLINE oAuth2ConsentSessionExpiresAtParContextL #-}

-- | 'oAuth2ConsentSessionExpiresAtRefreshToken' Lens
oAuth2ConsentSessionExpiresAtRefreshTokenL :: Lens_' OAuth2ConsentSessionExpiresAt (Maybe DateTime)
oAuth2ConsentSessionExpiresAtRefreshTokenL f OAuth2ConsentSessionExpiresAt{..} = (\oAuth2ConsentSessionExpiresAtRefreshToken -> OAuth2ConsentSessionExpiresAt { oAuth2ConsentSessionExpiresAtRefreshToken, ..} ) <$> f oAuth2ConsentSessionExpiresAtRefreshToken
{-# INLINE oAuth2ConsentSessionExpiresAtRefreshTokenL #-}



-- * OAuth2LoginRequest

-- | 'oAuth2LoginRequestChallenge' Lens
oAuth2LoginRequestChallengeL :: Lens_' OAuth2LoginRequest (Text)
oAuth2LoginRequestChallengeL f OAuth2LoginRequest{..} = (\oAuth2LoginRequestChallenge -> OAuth2LoginRequest { oAuth2LoginRequestChallenge, ..} ) <$> f oAuth2LoginRequestChallenge
{-# INLINE oAuth2LoginRequestChallengeL #-}

-- | 'oAuth2LoginRequestClient' Lens
oAuth2LoginRequestClientL :: Lens_' OAuth2LoginRequest (OAuth2Client)
oAuth2LoginRequestClientL f OAuth2LoginRequest{..} = (\oAuth2LoginRequestClient -> OAuth2LoginRequest { oAuth2LoginRequestClient, ..} ) <$> f oAuth2LoginRequestClient
{-# INLINE oAuth2LoginRequestClientL #-}

-- | 'oAuth2LoginRequestOidcContext' Lens
oAuth2LoginRequestOidcContextL :: Lens_' OAuth2LoginRequest (Maybe OAuth2ConsentRequestOpenIDConnectContext)
oAuth2LoginRequestOidcContextL f OAuth2LoginRequest{..} = (\oAuth2LoginRequestOidcContext -> OAuth2LoginRequest { oAuth2LoginRequestOidcContext, ..} ) <$> f oAuth2LoginRequestOidcContext
{-# INLINE oAuth2LoginRequestOidcContextL #-}

-- | 'oAuth2LoginRequestRequestUrl' Lens
oAuth2LoginRequestRequestUrlL :: Lens_' OAuth2LoginRequest (Text)
oAuth2LoginRequestRequestUrlL f OAuth2LoginRequest{..} = (\oAuth2LoginRequestRequestUrl -> OAuth2LoginRequest { oAuth2LoginRequestRequestUrl, ..} ) <$> f oAuth2LoginRequestRequestUrl
{-# INLINE oAuth2LoginRequestRequestUrlL #-}

-- | 'oAuth2LoginRequestRequestedAccessTokenAudience' Lens
oAuth2LoginRequestRequestedAccessTokenAudienceL :: Lens_' OAuth2LoginRequest ([Text])
oAuth2LoginRequestRequestedAccessTokenAudienceL f OAuth2LoginRequest{..} = (\oAuth2LoginRequestRequestedAccessTokenAudience -> OAuth2LoginRequest { oAuth2LoginRequestRequestedAccessTokenAudience, ..} ) <$> f oAuth2LoginRequestRequestedAccessTokenAudience
{-# INLINE oAuth2LoginRequestRequestedAccessTokenAudienceL #-}

-- | 'oAuth2LoginRequestRequestedScope' Lens
oAuth2LoginRequestRequestedScopeL :: Lens_' OAuth2LoginRequest ([Text])
oAuth2LoginRequestRequestedScopeL f OAuth2LoginRequest{..} = (\oAuth2LoginRequestRequestedScope -> OAuth2LoginRequest { oAuth2LoginRequestRequestedScope, ..} ) <$> f oAuth2LoginRequestRequestedScope
{-# INLINE oAuth2LoginRequestRequestedScopeL #-}

-- | 'oAuth2LoginRequestSessionId' Lens
oAuth2LoginRequestSessionIdL :: Lens_' OAuth2LoginRequest (Maybe Text)
oAuth2LoginRequestSessionIdL f OAuth2LoginRequest{..} = (\oAuth2LoginRequestSessionId -> OAuth2LoginRequest { oAuth2LoginRequestSessionId, ..} ) <$> f oAuth2LoginRequestSessionId
{-# INLINE oAuth2LoginRequestSessionIdL #-}

-- | 'oAuth2LoginRequestSkip' Lens
oAuth2LoginRequestSkipL :: Lens_' OAuth2LoginRequest (Bool)
oAuth2LoginRequestSkipL f OAuth2LoginRequest{..} = (\oAuth2LoginRequestSkip -> OAuth2LoginRequest { oAuth2LoginRequestSkip, ..} ) <$> f oAuth2LoginRequestSkip
{-# INLINE oAuth2LoginRequestSkipL #-}

-- | 'oAuth2LoginRequestSubject' Lens
oAuth2LoginRequestSubjectL :: Lens_' OAuth2LoginRequest (Text)
oAuth2LoginRequestSubjectL f OAuth2LoginRequest{..} = (\oAuth2LoginRequestSubject -> OAuth2LoginRequest { oAuth2LoginRequestSubject, ..} ) <$> f oAuth2LoginRequestSubject
{-# INLINE oAuth2LoginRequestSubjectL #-}



-- * OAuth2LogoutRequest

-- | 'oAuth2LogoutRequestChallenge' Lens
oAuth2LogoutRequestChallengeL :: Lens_' OAuth2LogoutRequest (Maybe Text)
oAuth2LogoutRequestChallengeL f OAuth2LogoutRequest{..} = (\oAuth2LogoutRequestChallenge -> OAuth2LogoutRequest { oAuth2LogoutRequestChallenge, ..} ) <$> f oAuth2LogoutRequestChallenge
{-# INLINE oAuth2LogoutRequestChallengeL #-}

-- | 'oAuth2LogoutRequestClient' Lens
oAuth2LogoutRequestClientL :: Lens_' OAuth2LogoutRequest (Maybe OAuth2Client)
oAuth2LogoutRequestClientL f OAuth2LogoutRequest{..} = (\oAuth2LogoutRequestClient -> OAuth2LogoutRequest { oAuth2LogoutRequestClient, ..} ) <$> f oAuth2LogoutRequestClient
{-# INLINE oAuth2LogoutRequestClientL #-}

-- | 'oAuth2LogoutRequestRequestUrl' Lens
oAuth2LogoutRequestRequestUrlL :: Lens_' OAuth2LogoutRequest (Maybe Text)
oAuth2LogoutRequestRequestUrlL f OAuth2LogoutRequest{..} = (\oAuth2LogoutRequestRequestUrl -> OAuth2LogoutRequest { oAuth2LogoutRequestRequestUrl, ..} ) <$> f oAuth2LogoutRequestRequestUrl
{-# INLINE oAuth2LogoutRequestRequestUrlL #-}

-- | 'oAuth2LogoutRequestRpInitiated' Lens
oAuth2LogoutRequestRpInitiatedL :: Lens_' OAuth2LogoutRequest (Maybe Bool)
oAuth2LogoutRequestRpInitiatedL f OAuth2LogoutRequest{..} = (\oAuth2LogoutRequestRpInitiated -> OAuth2LogoutRequest { oAuth2LogoutRequestRpInitiated, ..} ) <$> f oAuth2LogoutRequestRpInitiated
{-# INLINE oAuth2LogoutRequestRpInitiatedL #-}

-- | 'oAuth2LogoutRequestSid' Lens
oAuth2LogoutRequestSidL :: Lens_' OAuth2LogoutRequest (Maybe Text)
oAuth2LogoutRequestSidL f OAuth2LogoutRequest{..} = (\oAuth2LogoutRequestSid -> OAuth2LogoutRequest { oAuth2LogoutRequestSid, ..} ) <$> f oAuth2LogoutRequestSid
{-# INLINE oAuth2LogoutRequestSidL #-}

-- | 'oAuth2LogoutRequestSubject' Lens
oAuth2LogoutRequestSubjectL :: Lens_' OAuth2LogoutRequest (Maybe Text)
oAuth2LogoutRequestSubjectL f OAuth2LogoutRequest{..} = (\oAuth2LogoutRequestSubject -> OAuth2LogoutRequest { oAuth2LogoutRequestSubject, ..} ) <$> f oAuth2LogoutRequestSubject
{-# INLINE oAuth2LogoutRequestSubjectL #-}



-- * OAuth2RedirectTo

-- | 'oAuth2RedirectToRedirectTo' Lens
oAuth2RedirectToRedirectToL :: Lens_' OAuth2RedirectTo (Text)
oAuth2RedirectToRedirectToL f OAuth2RedirectTo{..} = (\oAuth2RedirectToRedirectTo -> OAuth2RedirectTo { oAuth2RedirectToRedirectTo, ..} ) <$> f oAuth2RedirectToRedirectTo
{-# INLINE oAuth2RedirectToRedirectToL #-}



-- * OAuth2TokenExchange

-- | 'oAuth2TokenExchangeAccessToken' Lens
oAuth2TokenExchangeAccessTokenL :: Lens_' OAuth2TokenExchange (Maybe Text)
oAuth2TokenExchangeAccessTokenL f OAuth2TokenExchange{..} = (\oAuth2TokenExchangeAccessToken -> OAuth2TokenExchange { oAuth2TokenExchangeAccessToken, ..} ) <$> f oAuth2TokenExchangeAccessToken
{-# INLINE oAuth2TokenExchangeAccessTokenL #-}

-- | 'oAuth2TokenExchangeExpiresIn' Lens
oAuth2TokenExchangeExpiresInL :: Lens_' OAuth2TokenExchange (Maybe Integer)
oAuth2TokenExchangeExpiresInL f OAuth2TokenExchange{..} = (\oAuth2TokenExchangeExpiresIn -> OAuth2TokenExchange { oAuth2TokenExchangeExpiresIn, ..} ) <$> f oAuth2TokenExchangeExpiresIn
{-# INLINE oAuth2TokenExchangeExpiresInL #-}

-- | 'oAuth2TokenExchangeIdToken' Lens
oAuth2TokenExchangeIdTokenL :: Lens_' OAuth2TokenExchange (Maybe Integer)
oAuth2TokenExchangeIdTokenL f OAuth2TokenExchange{..} = (\oAuth2TokenExchangeIdToken -> OAuth2TokenExchange { oAuth2TokenExchangeIdToken, ..} ) <$> f oAuth2TokenExchangeIdToken
{-# INLINE oAuth2TokenExchangeIdTokenL #-}

-- | 'oAuth2TokenExchangeRefreshToken' Lens
oAuth2TokenExchangeRefreshTokenL :: Lens_' OAuth2TokenExchange (Maybe Text)
oAuth2TokenExchangeRefreshTokenL f OAuth2TokenExchange{..} = (\oAuth2TokenExchangeRefreshToken -> OAuth2TokenExchange { oAuth2TokenExchangeRefreshToken, ..} ) <$> f oAuth2TokenExchangeRefreshToken
{-# INLINE oAuth2TokenExchangeRefreshTokenL #-}

-- | 'oAuth2TokenExchangeScope' Lens
oAuth2TokenExchangeScopeL :: Lens_' OAuth2TokenExchange (Maybe Text)
oAuth2TokenExchangeScopeL f OAuth2TokenExchange{..} = (\oAuth2TokenExchangeScope -> OAuth2TokenExchange { oAuth2TokenExchangeScope, ..} ) <$> f oAuth2TokenExchangeScope
{-# INLINE oAuth2TokenExchangeScopeL #-}

-- | 'oAuth2TokenExchangeTokenType' Lens
oAuth2TokenExchangeTokenTypeL :: Lens_' OAuth2TokenExchange (Maybe Text)
oAuth2TokenExchangeTokenTypeL f OAuth2TokenExchange{..} = (\oAuth2TokenExchangeTokenType -> OAuth2TokenExchange { oAuth2TokenExchangeTokenType, ..} ) <$> f oAuth2TokenExchangeTokenType
{-# INLINE oAuth2TokenExchangeTokenTypeL #-}



-- * OidcConfiguration

-- | 'oidcConfigurationAuthorizationEndpoint' Lens
oidcConfigurationAuthorizationEndpointL :: Lens_' OidcConfiguration (Text)
oidcConfigurationAuthorizationEndpointL f OidcConfiguration{..} = (\oidcConfigurationAuthorizationEndpoint -> OidcConfiguration { oidcConfigurationAuthorizationEndpoint, ..} ) <$> f oidcConfigurationAuthorizationEndpoint
{-# INLINE oidcConfigurationAuthorizationEndpointL #-}

-- | 'oidcConfigurationBackchannelLogoutSessionSupported' Lens
oidcConfigurationBackchannelLogoutSessionSupportedL :: Lens_' OidcConfiguration (Maybe Bool)
oidcConfigurationBackchannelLogoutSessionSupportedL f OidcConfiguration{..} = (\oidcConfigurationBackchannelLogoutSessionSupported -> OidcConfiguration { oidcConfigurationBackchannelLogoutSessionSupported, ..} ) <$> f oidcConfigurationBackchannelLogoutSessionSupported
{-# INLINE oidcConfigurationBackchannelLogoutSessionSupportedL #-}

-- | 'oidcConfigurationBackchannelLogoutSupported' Lens
oidcConfigurationBackchannelLogoutSupportedL :: Lens_' OidcConfiguration (Maybe Bool)
oidcConfigurationBackchannelLogoutSupportedL f OidcConfiguration{..} = (\oidcConfigurationBackchannelLogoutSupported -> OidcConfiguration { oidcConfigurationBackchannelLogoutSupported, ..} ) <$> f oidcConfigurationBackchannelLogoutSupported
{-# INLINE oidcConfigurationBackchannelLogoutSupportedL #-}

-- | 'oidcConfigurationClaimsParameterSupported' Lens
oidcConfigurationClaimsParameterSupportedL :: Lens_' OidcConfiguration (Maybe Bool)
oidcConfigurationClaimsParameterSupportedL f OidcConfiguration{..} = (\oidcConfigurationClaimsParameterSupported -> OidcConfiguration { oidcConfigurationClaimsParameterSupported, ..} ) <$> f oidcConfigurationClaimsParameterSupported
{-# INLINE oidcConfigurationClaimsParameterSupportedL #-}

-- | 'oidcConfigurationClaimsSupported' Lens
oidcConfigurationClaimsSupportedL :: Lens_' OidcConfiguration (Maybe [Text])
oidcConfigurationClaimsSupportedL f OidcConfiguration{..} = (\oidcConfigurationClaimsSupported -> OidcConfiguration { oidcConfigurationClaimsSupported, ..} ) <$> f oidcConfigurationClaimsSupported
{-# INLINE oidcConfigurationClaimsSupportedL #-}

-- | 'oidcConfigurationCodeChallengeMethodsSupported' Lens
oidcConfigurationCodeChallengeMethodsSupportedL :: Lens_' OidcConfiguration (Maybe [Text])
oidcConfigurationCodeChallengeMethodsSupportedL f OidcConfiguration{..} = (\oidcConfigurationCodeChallengeMethodsSupported -> OidcConfiguration { oidcConfigurationCodeChallengeMethodsSupported, ..} ) <$> f oidcConfigurationCodeChallengeMethodsSupported
{-# INLINE oidcConfigurationCodeChallengeMethodsSupportedL #-}

-- | 'oidcConfigurationEndSessionEndpoint' Lens
oidcConfigurationEndSessionEndpointL :: Lens_' OidcConfiguration (Maybe Text)
oidcConfigurationEndSessionEndpointL f OidcConfiguration{..} = (\oidcConfigurationEndSessionEndpoint -> OidcConfiguration { oidcConfigurationEndSessionEndpoint, ..} ) <$> f oidcConfigurationEndSessionEndpoint
{-# INLINE oidcConfigurationEndSessionEndpointL #-}

-- | 'oidcConfigurationFrontchannelLogoutSessionSupported' Lens
oidcConfigurationFrontchannelLogoutSessionSupportedL :: Lens_' OidcConfiguration (Maybe Bool)
oidcConfigurationFrontchannelLogoutSessionSupportedL f OidcConfiguration{..} = (\oidcConfigurationFrontchannelLogoutSessionSupported -> OidcConfiguration { oidcConfigurationFrontchannelLogoutSessionSupported, ..} ) <$> f oidcConfigurationFrontchannelLogoutSessionSupported
{-# INLINE oidcConfigurationFrontchannelLogoutSessionSupportedL #-}

-- | 'oidcConfigurationFrontchannelLogoutSupported' Lens
oidcConfigurationFrontchannelLogoutSupportedL :: Lens_' OidcConfiguration (Maybe Bool)
oidcConfigurationFrontchannelLogoutSupportedL f OidcConfiguration{..} = (\oidcConfigurationFrontchannelLogoutSupported -> OidcConfiguration { oidcConfigurationFrontchannelLogoutSupported, ..} ) <$> f oidcConfigurationFrontchannelLogoutSupported
{-# INLINE oidcConfigurationFrontchannelLogoutSupportedL #-}

-- | 'oidcConfigurationGrantTypesSupported' Lens
oidcConfigurationGrantTypesSupportedL :: Lens_' OidcConfiguration (Maybe [Text])
oidcConfigurationGrantTypesSupportedL f OidcConfiguration{..} = (\oidcConfigurationGrantTypesSupported -> OidcConfiguration { oidcConfigurationGrantTypesSupported, ..} ) <$> f oidcConfigurationGrantTypesSupported
{-# INLINE oidcConfigurationGrantTypesSupportedL #-}

-- | 'oidcConfigurationIdTokenSignedResponseAlg' Lens
oidcConfigurationIdTokenSignedResponseAlgL :: Lens_' OidcConfiguration ([Text])
oidcConfigurationIdTokenSignedResponseAlgL f OidcConfiguration{..} = (\oidcConfigurationIdTokenSignedResponseAlg -> OidcConfiguration { oidcConfigurationIdTokenSignedResponseAlg, ..} ) <$> f oidcConfigurationIdTokenSignedResponseAlg
{-# INLINE oidcConfigurationIdTokenSignedResponseAlgL #-}

-- | 'oidcConfigurationIdTokenSigningAlgValuesSupported' Lens
oidcConfigurationIdTokenSigningAlgValuesSupportedL :: Lens_' OidcConfiguration ([Text])
oidcConfigurationIdTokenSigningAlgValuesSupportedL f OidcConfiguration{..} = (\oidcConfigurationIdTokenSigningAlgValuesSupported -> OidcConfiguration { oidcConfigurationIdTokenSigningAlgValuesSupported, ..} ) <$> f oidcConfigurationIdTokenSigningAlgValuesSupported
{-# INLINE oidcConfigurationIdTokenSigningAlgValuesSupportedL #-}

-- | 'oidcConfigurationIssuer' Lens
oidcConfigurationIssuerL :: Lens_' OidcConfiguration (Text)
oidcConfigurationIssuerL f OidcConfiguration{..} = (\oidcConfigurationIssuer -> OidcConfiguration { oidcConfigurationIssuer, ..} ) <$> f oidcConfigurationIssuer
{-# INLINE oidcConfigurationIssuerL #-}

-- | 'oidcConfigurationJwksUri' Lens
oidcConfigurationJwksUriL :: Lens_' OidcConfiguration (Text)
oidcConfigurationJwksUriL f OidcConfiguration{..} = (\oidcConfigurationJwksUri -> OidcConfiguration { oidcConfigurationJwksUri, ..} ) <$> f oidcConfigurationJwksUri
{-# INLINE oidcConfigurationJwksUriL #-}

-- | 'oidcConfigurationRegistrationEndpoint' Lens
oidcConfigurationRegistrationEndpointL :: Lens_' OidcConfiguration (Maybe Text)
oidcConfigurationRegistrationEndpointL f OidcConfiguration{..} = (\oidcConfigurationRegistrationEndpoint -> OidcConfiguration { oidcConfigurationRegistrationEndpoint, ..} ) <$> f oidcConfigurationRegistrationEndpoint
{-# INLINE oidcConfigurationRegistrationEndpointL #-}

-- | 'oidcConfigurationRequestObjectSigningAlgValuesSupported' Lens
oidcConfigurationRequestObjectSigningAlgValuesSupportedL :: Lens_' OidcConfiguration (Maybe [Text])
oidcConfigurationRequestObjectSigningAlgValuesSupportedL f OidcConfiguration{..} = (\oidcConfigurationRequestObjectSigningAlgValuesSupported -> OidcConfiguration { oidcConfigurationRequestObjectSigningAlgValuesSupported, ..} ) <$> f oidcConfigurationRequestObjectSigningAlgValuesSupported
{-# INLINE oidcConfigurationRequestObjectSigningAlgValuesSupportedL #-}

-- | 'oidcConfigurationRequestParameterSupported' Lens
oidcConfigurationRequestParameterSupportedL :: Lens_' OidcConfiguration (Maybe Bool)
oidcConfigurationRequestParameterSupportedL f OidcConfiguration{..} = (\oidcConfigurationRequestParameterSupported -> OidcConfiguration { oidcConfigurationRequestParameterSupported, ..} ) <$> f oidcConfigurationRequestParameterSupported
{-# INLINE oidcConfigurationRequestParameterSupportedL #-}

-- | 'oidcConfigurationRequestUriParameterSupported' Lens
oidcConfigurationRequestUriParameterSupportedL :: Lens_' OidcConfiguration (Maybe Bool)
oidcConfigurationRequestUriParameterSupportedL f OidcConfiguration{..} = (\oidcConfigurationRequestUriParameterSupported -> OidcConfiguration { oidcConfigurationRequestUriParameterSupported, ..} ) <$> f oidcConfigurationRequestUriParameterSupported
{-# INLINE oidcConfigurationRequestUriParameterSupportedL #-}

-- | 'oidcConfigurationRequireRequestUriRegistration' Lens
oidcConfigurationRequireRequestUriRegistrationL :: Lens_' OidcConfiguration (Maybe Bool)
oidcConfigurationRequireRequestUriRegistrationL f OidcConfiguration{..} = (\oidcConfigurationRequireRequestUriRegistration -> OidcConfiguration { oidcConfigurationRequireRequestUriRegistration, ..} ) <$> f oidcConfigurationRequireRequestUriRegistration
{-# INLINE oidcConfigurationRequireRequestUriRegistrationL #-}

-- | 'oidcConfigurationResponseModesSupported' Lens
oidcConfigurationResponseModesSupportedL :: Lens_' OidcConfiguration (Maybe [Text])
oidcConfigurationResponseModesSupportedL f OidcConfiguration{..} = (\oidcConfigurationResponseModesSupported -> OidcConfiguration { oidcConfigurationResponseModesSupported, ..} ) <$> f oidcConfigurationResponseModesSupported
{-# INLINE oidcConfigurationResponseModesSupportedL #-}

-- | 'oidcConfigurationResponseTypesSupported' Lens
oidcConfigurationResponseTypesSupportedL :: Lens_' OidcConfiguration ([Text])
oidcConfigurationResponseTypesSupportedL f OidcConfiguration{..} = (\oidcConfigurationResponseTypesSupported -> OidcConfiguration { oidcConfigurationResponseTypesSupported, ..} ) <$> f oidcConfigurationResponseTypesSupported
{-# INLINE oidcConfigurationResponseTypesSupportedL #-}

-- | 'oidcConfigurationRevocationEndpoint' Lens
oidcConfigurationRevocationEndpointL :: Lens_' OidcConfiguration (Maybe Text)
oidcConfigurationRevocationEndpointL f OidcConfiguration{..} = (\oidcConfigurationRevocationEndpoint -> OidcConfiguration { oidcConfigurationRevocationEndpoint, ..} ) <$> f oidcConfigurationRevocationEndpoint
{-# INLINE oidcConfigurationRevocationEndpointL #-}

-- | 'oidcConfigurationScopesSupported' Lens
oidcConfigurationScopesSupportedL :: Lens_' OidcConfiguration (Maybe [Text])
oidcConfigurationScopesSupportedL f OidcConfiguration{..} = (\oidcConfigurationScopesSupported -> OidcConfiguration { oidcConfigurationScopesSupported, ..} ) <$> f oidcConfigurationScopesSupported
{-# INLINE oidcConfigurationScopesSupportedL #-}

-- | 'oidcConfigurationSubjectTypesSupported' Lens
oidcConfigurationSubjectTypesSupportedL :: Lens_' OidcConfiguration ([Text])
oidcConfigurationSubjectTypesSupportedL f OidcConfiguration{..} = (\oidcConfigurationSubjectTypesSupported -> OidcConfiguration { oidcConfigurationSubjectTypesSupported, ..} ) <$> f oidcConfigurationSubjectTypesSupported
{-# INLINE oidcConfigurationSubjectTypesSupportedL #-}

-- | 'oidcConfigurationTokenEndpoint' Lens
oidcConfigurationTokenEndpointL :: Lens_' OidcConfiguration (Text)
oidcConfigurationTokenEndpointL f OidcConfiguration{..} = (\oidcConfigurationTokenEndpoint -> OidcConfiguration { oidcConfigurationTokenEndpoint, ..} ) <$> f oidcConfigurationTokenEndpoint
{-# INLINE oidcConfigurationTokenEndpointL #-}

-- | 'oidcConfigurationTokenEndpointAuthMethodsSupported' Lens
oidcConfigurationTokenEndpointAuthMethodsSupportedL :: Lens_' OidcConfiguration (Maybe [Text])
oidcConfigurationTokenEndpointAuthMethodsSupportedL f OidcConfiguration{..} = (\oidcConfigurationTokenEndpointAuthMethodsSupported -> OidcConfiguration { oidcConfigurationTokenEndpointAuthMethodsSupported, ..} ) <$> f oidcConfigurationTokenEndpointAuthMethodsSupported
{-# INLINE oidcConfigurationTokenEndpointAuthMethodsSupportedL #-}

-- | 'oidcConfigurationUserinfoEndpoint' Lens
oidcConfigurationUserinfoEndpointL :: Lens_' OidcConfiguration (Maybe Text)
oidcConfigurationUserinfoEndpointL f OidcConfiguration{..} = (\oidcConfigurationUserinfoEndpoint -> OidcConfiguration { oidcConfigurationUserinfoEndpoint, ..} ) <$> f oidcConfigurationUserinfoEndpoint
{-# INLINE oidcConfigurationUserinfoEndpointL #-}

-- | 'oidcConfigurationUserinfoSignedResponseAlg' Lens
oidcConfigurationUserinfoSignedResponseAlgL :: Lens_' OidcConfiguration ([Text])
oidcConfigurationUserinfoSignedResponseAlgL f OidcConfiguration{..} = (\oidcConfigurationUserinfoSignedResponseAlg -> OidcConfiguration { oidcConfigurationUserinfoSignedResponseAlg, ..} ) <$> f oidcConfigurationUserinfoSignedResponseAlg
{-# INLINE oidcConfigurationUserinfoSignedResponseAlgL #-}

-- | 'oidcConfigurationUserinfoSigningAlgValuesSupported' Lens
oidcConfigurationUserinfoSigningAlgValuesSupportedL :: Lens_' OidcConfiguration (Maybe [Text])
oidcConfigurationUserinfoSigningAlgValuesSupportedL f OidcConfiguration{..} = (\oidcConfigurationUserinfoSigningAlgValuesSupported -> OidcConfiguration { oidcConfigurationUserinfoSigningAlgValuesSupported, ..} ) <$> f oidcConfigurationUserinfoSigningAlgValuesSupported
{-# INLINE oidcConfigurationUserinfoSigningAlgValuesSupportedL #-}



-- * OidcUserInfo

-- | 'oidcUserInfoBirthdate' Lens
oidcUserInfoBirthdateL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoBirthdateL f OidcUserInfo{..} = (\oidcUserInfoBirthdate -> OidcUserInfo { oidcUserInfoBirthdate, ..} ) <$> f oidcUserInfoBirthdate
{-# INLINE oidcUserInfoBirthdateL #-}

-- | 'oidcUserInfoEmail' Lens
oidcUserInfoEmailL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoEmailL f OidcUserInfo{..} = (\oidcUserInfoEmail -> OidcUserInfo { oidcUserInfoEmail, ..} ) <$> f oidcUserInfoEmail
{-# INLINE oidcUserInfoEmailL #-}

-- | 'oidcUserInfoEmailVerified' Lens
oidcUserInfoEmailVerifiedL :: Lens_' OidcUserInfo (Maybe Bool)
oidcUserInfoEmailVerifiedL f OidcUserInfo{..} = (\oidcUserInfoEmailVerified -> OidcUserInfo { oidcUserInfoEmailVerified, ..} ) <$> f oidcUserInfoEmailVerified
{-# INLINE oidcUserInfoEmailVerifiedL #-}

-- | 'oidcUserInfoFamilyName' Lens
oidcUserInfoFamilyNameL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoFamilyNameL f OidcUserInfo{..} = (\oidcUserInfoFamilyName -> OidcUserInfo { oidcUserInfoFamilyName, ..} ) <$> f oidcUserInfoFamilyName
{-# INLINE oidcUserInfoFamilyNameL #-}

-- | 'oidcUserInfoGender' Lens
oidcUserInfoGenderL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoGenderL f OidcUserInfo{..} = (\oidcUserInfoGender -> OidcUserInfo { oidcUserInfoGender, ..} ) <$> f oidcUserInfoGender
{-# INLINE oidcUserInfoGenderL #-}

-- | 'oidcUserInfoGivenName' Lens
oidcUserInfoGivenNameL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoGivenNameL f OidcUserInfo{..} = (\oidcUserInfoGivenName -> OidcUserInfo { oidcUserInfoGivenName, ..} ) <$> f oidcUserInfoGivenName
{-# INLINE oidcUserInfoGivenNameL #-}

-- | 'oidcUserInfoLocale' Lens
oidcUserInfoLocaleL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoLocaleL f OidcUserInfo{..} = (\oidcUserInfoLocale -> OidcUserInfo { oidcUserInfoLocale, ..} ) <$> f oidcUserInfoLocale
{-# INLINE oidcUserInfoLocaleL #-}

-- | 'oidcUserInfoMiddleName' Lens
oidcUserInfoMiddleNameL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoMiddleNameL f OidcUserInfo{..} = (\oidcUserInfoMiddleName -> OidcUserInfo { oidcUserInfoMiddleName, ..} ) <$> f oidcUserInfoMiddleName
{-# INLINE oidcUserInfoMiddleNameL #-}

-- | 'oidcUserInfoName' Lens
oidcUserInfoNameL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoNameL f OidcUserInfo{..} = (\oidcUserInfoName -> OidcUserInfo { oidcUserInfoName, ..} ) <$> f oidcUserInfoName
{-# INLINE oidcUserInfoNameL #-}

-- | 'oidcUserInfoNickname' Lens
oidcUserInfoNicknameL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoNicknameL f OidcUserInfo{..} = (\oidcUserInfoNickname -> OidcUserInfo { oidcUserInfoNickname, ..} ) <$> f oidcUserInfoNickname
{-# INLINE oidcUserInfoNicknameL #-}

-- | 'oidcUserInfoPhoneNumber' Lens
oidcUserInfoPhoneNumberL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoPhoneNumberL f OidcUserInfo{..} = (\oidcUserInfoPhoneNumber -> OidcUserInfo { oidcUserInfoPhoneNumber, ..} ) <$> f oidcUserInfoPhoneNumber
{-# INLINE oidcUserInfoPhoneNumberL #-}

-- | 'oidcUserInfoPhoneNumberVerified' Lens
oidcUserInfoPhoneNumberVerifiedL :: Lens_' OidcUserInfo (Maybe Bool)
oidcUserInfoPhoneNumberVerifiedL f OidcUserInfo{..} = (\oidcUserInfoPhoneNumberVerified -> OidcUserInfo { oidcUserInfoPhoneNumberVerified, ..} ) <$> f oidcUserInfoPhoneNumberVerified
{-# INLINE oidcUserInfoPhoneNumberVerifiedL #-}

-- | 'oidcUserInfoPicture' Lens
oidcUserInfoPictureL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoPictureL f OidcUserInfo{..} = (\oidcUserInfoPicture -> OidcUserInfo { oidcUserInfoPicture, ..} ) <$> f oidcUserInfoPicture
{-# INLINE oidcUserInfoPictureL #-}

-- | 'oidcUserInfoPreferredUsername' Lens
oidcUserInfoPreferredUsernameL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoPreferredUsernameL f OidcUserInfo{..} = (\oidcUserInfoPreferredUsername -> OidcUserInfo { oidcUserInfoPreferredUsername, ..} ) <$> f oidcUserInfoPreferredUsername
{-# INLINE oidcUserInfoPreferredUsernameL #-}

-- | 'oidcUserInfoProfile' Lens
oidcUserInfoProfileL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoProfileL f OidcUserInfo{..} = (\oidcUserInfoProfile -> OidcUserInfo { oidcUserInfoProfile, ..} ) <$> f oidcUserInfoProfile
{-# INLINE oidcUserInfoProfileL #-}

-- | 'oidcUserInfoSub' Lens
oidcUserInfoSubL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoSubL f OidcUserInfo{..} = (\oidcUserInfoSub -> OidcUserInfo { oidcUserInfoSub, ..} ) <$> f oidcUserInfoSub
{-# INLINE oidcUserInfoSubL #-}

-- | 'oidcUserInfoUpdatedAt' Lens
oidcUserInfoUpdatedAtL :: Lens_' OidcUserInfo (Maybe Integer)
oidcUserInfoUpdatedAtL f OidcUserInfo{..} = (\oidcUserInfoUpdatedAt -> OidcUserInfo { oidcUserInfoUpdatedAt, ..} ) <$> f oidcUserInfoUpdatedAt
{-# INLINE oidcUserInfoUpdatedAtL #-}

-- | 'oidcUserInfoWebsite' Lens
oidcUserInfoWebsiteL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoWebsiteL f OidcUserInfo{..} = (\oidcUserInfoWebsite -> OidcUserInfo { oidcUserInfoWebsite, ..} ) <$> f oidcUserInfoWebsite
{-# INLINE oidcUserInfoWebsiteL #-}

-- | 'oidcUserInfoZoneinfo' Lens
oidcUserInfoZoneinfoL :: Lens_' OidcUserInfo (Maybe Text)
oidcUserInfoZoneinfoL f OidcUserInfo{..} = (\oidcUserInfoZoneinfo -> OidcUserInfo { oidcUserInfoZoneinfo, ..} ) <$> f oidcUserInfoZoneinfo
{-# INLINE oidcUserInfoZoneinfoL #-}



-- * Pagination

-- | 'paginationPageSize' Lens
paginationPageSizeL :: Lens_' Pagination (Maybe Integer)
paginationPageSizeL f Pagination{..} = (\paginationPageSize -> Pagination { paginationPageSize, ..} ) <$> f paginationPageSize
{-# INLINE paginationPageSizeL #-}

-- | 'paginationPageToken' Lens
paginationPageTokenL :: Lens_' Pagination (Maybe Text)
paginationPageTokenL f Pagination{..} = (\paginationPageToken -> Pagination { paginationPageToken, ..} ) <$> f paginationPageToken
{-# INLINE paginationPageTokenL #-}



-- * PaginationHeaders

-- | 'paginationHeadersLink' Lens
paginationHeadersLinkL :: Lens_' PaginationHeaders (Maybe Text)
paginationHeadersLinkL f PaginationHeaders{..} = (\paginationHeadersLink -> PaginationHeaders { paginationHeadersLink, ..} ) <$> f paginationHeadersLink
{-# INLINE paginationHeadersLinkL #-}

-- | 'paginationHeadersXTotalCount' Lens
paginationHeadersXTotalCountL :: Lens_' PaginationHeaders (Maybe Text)
paginationHeadersXTotalCountL f PaginationHeaders{..} = (\paginationHeadersXTotalCount -> PaginationHeaders { paginationHeadersXTotalCount, ..} ) <$> f paginationHeadersXTotalCount
{-# INLINE paginationHeadersXTotalCountL #-}



-- * RejectOAuth2Request

-- | 'rejectOAuth2RequestError' Lens
rejectOAuth2RequestErrorL :: Lens_' RejectOAuth2Request (Maybe Text)
rejectOAuth2RequestErrorL f RejectOAuth2Request{..} = (\rejectOAuth2RequestError -> RejectOAuth2Request { rejectOAuth2RequestError, ..} ) <$> f rejectOAuth2RequestError
{-# INLINE rejectOAuth2RequestErrorL #-}

-- | 'rejectOAuth2RequestErrorDebug' Lens
rejectOAuth2RequestErrorDebugL :: Lens_' RejectOAuth2Request (Maybe Text)
rejectOAuth2RequestErrorDebugL f RejectOAuth2Request{..} = (\rejectOAuth2RequestErrorDebug -> RejectOAuth2Request { rejectOAuth2RequestErrorDebug, ..} ) <$> f rejectOAuth2RequestErrorDebug
{-# INLINE rejectOAuth2RequestErrorDebugL #-}

-- | 'rejectOAuth2RequestErrorDescription' Lens
rejectOAuth2RequestErrorDescriptionL :: Lens_' RejectOAuth2Request (Maybe Text)
rejectOAuth2RequestErrorDescriptionL f RejectOAuth2Request{..} = (\rejectOAuth2RequestErrorDescription -> RejectOAuth2Request { rejectOAuth2RequestErrorDescription, ..} ) <$> f rejectOAuth2RequestErrorDescription
{-# INLINE rejectOAuth2RequestErrorDescriptionL #-}

-- | 'rejectOAuth2RequestErrorHint' Lens
rejectOAuth2RequestErrorHintL :: Lens_' RejectOAuth2Request (Maybe Text)
rejectOAuth2RequestErrorHintL f RejectOAuth2Request{..} = (\rejectOAuth2RequestErrorHint -> RejectOAuth2Request { rejectOAuth2RequestErrorHint, ..} ) <$> f rejectOAuth2RequestErrorHint
{-# INLINE rejectOAuth2RequestErrorHintL #-}

-- | 'rejectOAuth2RequestStatusCode' Lens
rejectOAuth2RequestStatusCodeL :: Lens_' RejectOAuth2Request (Maybe Integer)
rejectOAuth2RequestStatusCodeL f RejectOAuth2Request{..} = (\rejectOAuth2RequestStatusCode -> RejectOAuth2Request { rejectOAuth2RequestStatusCode, ..} ) <$> f rejectOAuth2RequestStatusCode
{-# INLINE rejectOAuth2RequestStatusCodeL #-}



-- * TokenPagination

-- | 'tokenPaginationPageSize' Lens
tokenPaginationPageSizeL :: Lens_' TokenPagination (Maybe Integer)
tokenPaginationPageSizeL f TokenPagination{..} = (\tokenPaginationPageSize -> TokenPagination { tokenPaginationPageSize, ..} ) <$> f tokenPaginationPageSize
{-# INLINE tokenPaginationPageSizeL #-}

-- | 'tokenPaginationPageToken' Lens
tokenPaginationPageTokenL :: Lens_' TokenPagination (Maybe Text)
tokenPaginationPageTokenL f TokenPagination{..} = (\tokenPaginationPageToken -> TokenPagination { tokenPaginationPageToken, ..} ) <$> f tokenPaginationPageToken
{-# INLINE tokenPaginationPageTokenL #-}



-- * TokenPaginationHeaders

-- | 'tokenPaginationHeadersLink' Lens
tokenPaginationHeadersLinkL :: Lens_' TokenPaginationHeaders (Maybe Text)
tokenPaginationHeadersLinkL f TokenPaginationHeaders{..} = (\tokenPaginationHeadersLink -> TokenPaginationHeaders { tokenPaginationHeadersLink, ..} ) <$> f tokenPaginationHeadersLink
{-# INLINE tokenPaginationHeadersLinkL #-}

-- | 'tokenPaginationHeadersXTotalCount' Lens
tokenPaginationHeadersXTotalCountL :: Lens_' TokenPaginationHeaders (Maybe Text)
tokenPaginationHeadersXTotalCountL f TokenPaginationHeaders{..} = (\tokenPaginationHeadersXTotalCount -> TokenPaginationHeaders { tokenPaginationHeadersXTotalCount, ..} ) <$> f tokenPaginationHeadersXTotalCount
{-# INLINE tokenPaginationHeadersXTotalCountL #-}



-- * TokenPaginationRequestParameters

-- | 'tokenPaginationRequestParametersPageSize' Lens
tokenPaginationRequestParametersPageSizeL :: Lens_' TokenPaginationRequestParameters (Maybe Integer)
tokenPaginationRequestParametersPageSizeL f TokenPaginationRequestParameters{..} = (\tokenPaginationRequestParametersPageSize -> TokenPaginationRequestParameters { tokenPaginationRequestParametersPageSize, ..} ) <$> f tokenPaginationRequestParametersPageSize
{-# INLINE tokenPaginationRequestParametersPageSizeL #-}

-- | 'tokenPaginationRequestParametersPageToken' Lens
tokenPaginationRequestParametersPageTokenL :: Lens_' TokenPaginationRequestParameters (Maybe Text)
tokenPaginationRequestParametersPageTokenL f TokenPaginationRequestParameters{..} = (\tokenPaginationRequestParametersPageToken -> TokenPaginationRequestParameters { tokenPaginationRequestParametersPageToken, ..} ) <$> f tokenPaginationRequestParametersPageToken
{-# INLINE tokenPaginationRequestParametersPageTokenL #-}



-- * TokenPaginationResponseHeaders

-- | 'tokenPaginationResponseHeadersLink' Lens
tokenPaginationResponseHeadersLinkL :: Lens_' TokenPaginationResponseHeaders (Maybe Text)
tokenPaginationResponseHeadersLinkL f TokenPaginationResponseHeaders{..} = (\tokenPaginationResponseHeadersLink -> TokenPaginationResponseHeaders { tokenPaginationResponseHeadersLink, ..} ) <$> f tokenPaginationResponseHeadersLink
{-# INLINE tokenPaginationResponseHeadersLinkL #-}

-- | 'tokenPaginationResponseHeadersXTotalCount' Lens
tokenPaginationResponseHeadersXTotalCountL :: Lens_' TokenPaginationResponseHeaders (Maybe Integer)
tokenPaginationResponseHeadersXTotalCountL f TokenPaginationResponseHeaders{..} = (\tokenPaginationResponseHeadersXTotalCount -> TokenPaginationResponseHeaders { tokenPaginationResponseHeadersXTotalCount, ..} ) <$> f tokenPaginationResponseHeadersXTotalCount
{-# INLINE tokenPaginationResponseHeadersXTotalCountL #-}



-- * TrustOAuth2JwtGrantIssuer

-- | 'trustOAuth2JwtGrantIssuerAllowAnySubject' Lens
trustOAuth2JwtGrantIssuerAllowAnySubjectL :: Lens_' TrustOAuth2JwtGrantIssuer (Maybe Bool)
trustOAuth2JwtGrantIssuerAllowAnySubjectL f TrustOAuth2JwtGrantIssuer{..} = (\trustOAuth2JwtGrantIssuerAllowAnySubject -> TrustOAuth2JwtGrantIssuer { trustOAuth2JwtGrantIssuerAllowAnySubject, ..} ) <$> f trustOAuth2JwtGrantIssuerAllowAnySubject
{-# INLINE trustOAuth2JwtGrantIssuerAllowAnySubjectL #-}

-- | 'trustOAuth2JwtGrantIssuerExpiresAt' Lens
trustOAuth2JwtGrantIssuerExpiresAtL :: Lens_' TrustOAuth2JwtGrantIssuer (DateTime)
trustOAuth2JwtGrantIssuerExpiresAtL f TrustOAuth2JwtGrantIssuer{..} = (\trustOAuth2JwtGrantIssuerExpiresAt -> TrustOAuth2JwtGrantIssuer { trustOAuth2JwtGrantIssuerExpiresAt, ..} ) <$> f trustOAuth2JwtGrantIssuerExpiresAt
{-# INLINE trustOAuth2JwtGrantIssuerExpiresAtL #-}

-- | 'trustOAuth2JwtGrantIssuerIssuer' Lens
trustOAuth2JwtGrantIssuerIssuerL :: Lens_' TrustOAuth2JwtGrantIssuer (Text)
trustOAuth2JwtGrantIssuerIssuerL f TrustOAuth2JwtGrantIssuer{..} = (\trustOAuth2JwtGrantIssuerIssuer -> TrustOAuth2JwtGrantIssuer { trustOAuth2JwtGrantIssuerIssuer, ..} ) <$> f trustOAuth2JwtGrantIssuerIssuer
{-# INLINE trustOAuth2JwtGrantIssuerIssuerL #-}

-- | 'trustOAuth2JwtGrantIssuerJwk' Lens
trustOAuth2JwtGrantIssuerJwkL :: Lens_' TrustOAuth2JwtGrantIssuer (JsonWebKey)
trustOAuth2JwtGrantIssuerJwkL f TrustOAuth2JwtGrantIssuer{..} = (\trustOAuth2JwtGrantIssuerJwk -> TrustOAuth2JwtGrantIssuer { trustOAuth2JwtGrantIssuerJwk, ..} ) <$> f trustOAuth2JwtGrantIssuerJwk
{-# INLINE trustOAuth2JwtGrantIssuerJwkL #-}

-- | 'trustOAuth2JwtGrantIssuerScope' Lens
trustOAuth2JwtGrantIssuerScopeL :: Lens_' TrustOAuth2JwtGrantIssuer ([Text])
trustOAuth2JwtGrantIssuerScopeL f TrustOAuth2JwtGrantIssuer{..} = (\trustOAuth2JwtGrantIssuerScope -> TrustOAuth2JwtGrantIssuer { trustOAuth2JwtGrantIssuerScope, ..} ) <$> f trustOAuth2JwtGrantIssuerScope
{-# INLINE trustOAuth2JwtGrantIssuerScopeL #-}

-- | 'trustOAuth2JwtGrantIssuerSubject' Lens
trustOAuth2JwtGrantIssuerSubjectL :: Lens_' TrustOAuth2JwtGrantIssuer (Maybe Text)
trustOAuth2JwtGrantIssuerSubjectL f TrustOAuth2JwtGrantIssuer{..} = (\trustOAuth2JwtGrantIssuerSubject -> TrustOAuth2JwtGrantIssuer { trustOAuth2JwtGrantIssuerSubject, ..} ) <$> f trustOAuth2JwtGrantIssuerSubject
{-# INLINE trustOAuth2JwtGrantIssuerSubjectL #-}



-- * TrustedOAuth2JwtGrantIssuer

-- | 'trustedOAuth2JwtGrantIssuerAllowAnySubject' Lens
trustedOAuth2JwtGrantIssuerAllowAnySubjectL :: Lens_' TrustedOAuth2JwtGrantIssuer (Maybe Bool)
trustedOAuth2JwtGrantIssuerAllowAnySubjectL f TrustedOAuth2JwtGrantIssuer{..} = (\trustedOAuth2JwtGrantIssuerAllowAnySubject -> TrustedOAuth2JwtGrantIssuer { trustedOAuth2JwtGrantIssuerAllowAnySubject, ..} ) <$> f trustedOAuth2JwtGrantIssuerAllowAnySubject
{-# INLINE trustedOAuth2JwtGrantIssuerAllowAnySubjectL #-}

-- | 'trustedOAuth2JwtGrantIssuerCreatedAt' Lens
trustedOAuth2JwtGrantIssuerCreatedAtL :: Lens_' TrustedOAuth2JwtGrantIssuer (Maybe DateTime)
trustedOAuth2JwtGrantIssuerCreatedAtL f TrustedOAuth2JwtGrantIssuer{..} = (\trustedOAuth2JwtGrantIssuerCreatedAt -> TrustedOAuth2JwtGrantIssuer { trustedOAuth2JwtGrantIssuerCreatedAt, ..} ) <$> f trustedOAuth2JwtGrantIssuerCreatedAt
{-# INLINE trustedOAuth2JwtGrantIssuerCreatedAtL #-}

-- | 'trustedOAuth2JwtGrantIssuerExpiresAt' Lens
trustedOAuth2JwtGrantIssuerExpiresAtL :: Lens_' TrustedOAuth2JwtGrantIssuer (Maybe DateTime)
trustedOAuth2JwtGrantIssuerExpiresAtL f TrustedOAuth2JwtGrantIssuer{..} = (\trustedOAuth2JwtGrantIssuerExpiresAt -> TrustedOAuth2JwtGrantIssuer { trustedOAuth2JwtGrantIssuerExpiresAt, ..} ) <$> f trustedOAuth2JwtGrantIssuerExpiresAt
{-# INLINE trustedOAuth2JwtGrantIssuerExpiresAtL #-}

-- | 'trustedOAuth2JwtGrantIssuerId' Lens
trustedOAuth2JwtGrantIssuerIdL :: Lens_' TrustedOAuth2JwtGrantIssuer (Maybe Text)
trustedOAuth2JwtGrantIssuerIdL f TrustedOAuth2JwtGrantIssuer{..} = (\trustedOAuth2JwtGrantIssuerId -> TrustedOAuth2JwtGrantIssuer { trustedOAuth2JwtGrantIssuerId, ..} ) <$> f trustedOAuth2JwtGrantIssuerId
{-# INLINE trustedOAuth2JwtGrantIssuerIdL #-}

-- | 'trustedOAuth2JwtGrantIssuerIssuer' Lens
trustedOAuth2JwtGrantIssuerIssuerL :: Lens_' TrustedOAuth2JwtGrantIssuer (Maybe Text)
trustedOAuth2JwtGrantIssuerIssuerL f TrustedOAuth2JwtGrantIssuer{..} = (\trustedOAuth2JwtGrantIssuerIssuer -> TrustedOAuth2JwtGrantIssuer { trustedOAuth2JwtGrantIssuerIssuer, ..} ) <$> f trustedOAuth2JwtGrantIssuerIssuer
{-# INLINE trustedOAuth2JwtGrantIssuerIssuerL #-}

-- | 'trustedOAuth2JwtGrantIssuerPublicKey' Lens
trustedOAuth2JwtGrantIssuerPublicKeyL :: Lens_' TrustedOAuth2JwtGrantIssuer (Maybe TrustedOAuth2JwtGrantJsonWebKey)
trustedOAuth2JwtGrantIssuerPublicKeyL f TrustedOAuth2JwtGrantIssuer{..} = (\trustedOAuth2JwtGrantIssuerPublicKey -> TrustedOAuth2JwtGrantIssuer { trustedOAuth2JwtGrantIssuerPublicKey, ..} ) <$> f trustedOAuth2JwtGrantIssuerPublicKey
{-# INLINE trustedOAuth2JwtGrantIssuerPublicKeyL #-}

-- | 'trustedOAuth2JwtGrantIssuerScope' Lens
trustedOAuth2JwtGrantIssuerScopeL :: Lens_' TrustedOAuth2JwtGrantIssuer (Maybe [Text])
trustedOAuth2JwtGrantIssuerScopeL f TrustedOAuth2JwtGrantIssuer{..} = (\trustedOAuth2JwtGrantIssuerScope -> TrustedOAuth2JwtGrantIssuer { trustedOAuth2JwtGrantIssuerScope, ..} ) <$> f trustedOAuth2JwtGrantIssuerScope
{-# INLINE trustedOAuth2JwtGrantIssuerScopeL #-}

-- | 'trustedOAuth2JwtGrantIssuerSubject' Lens
trustedOAuth2JwtGrantIssuerSubjectL :: Lens_' TrustedOAuth2JwtGrantIssuer (Maybe Text)
trustedOAuth2JwtGrantIssuerSubjectL f TrustedOAuth2JwtGrantIssuer{..} = (\trustedOAuth2JwtGrantIssuerSubject -> TrustedOAuth2JwtGrantIssuer { trustedOAuth2JwtGrantIssuerSubject, ..} ) <$> f trustedOAuth2JwtGrantIssuerSubject
{-# INLINE trustedOAuth2JwtGrantIssuerSubjectL #-}



-- * TrustedOAuth2JwtGrantJsonWebKey

-- | 'trustedOAuth2JwtGrantJsonWebKeyKid' Lens
trustedOAuth2JwtGrantJsonWebKeyKidL :: Lens_' TrustedOAuth2JwtGrantJsonWebKey (Maybe Text)
trustedOAuth2JwtGrantJsonWebKeyKidL f TrustedOAuth2JwtGrantJsonWebKey{..} = (\trustedOAuth2JwtGrantJsonWebKeyKid -> TrustedOAuth2JwtGrantJsonWebKey { trustedOAuth2JwtGrantJsonWebKeyKid, ..} ) <$> f trustedOAuth2JwtGrantJsonWebKeyKid
{-# INLINE trustedOAuth2JwtGrantJsonWebKeyKidL #-}

-- | 'trustedOAuth2JwtGrantJsonWebKeySet' Lens
trustedOAuth2JwtGrantJsonWebKeySetL :: Lens_' TrustedOAuth2JwtGrantJsonWebKey (Maybe Text)
trustedOAuth2JwtGrantJsonWebKeySetL f TrustedOAuth2JwtGrantJsonWebKey{..} = (\trustedOAuth2JwtGrantJsonWebKeySet -> TrustedOAuth2JwtGrantJsonWebKey { trustedOAuth2JwtGrantJsonWebKeySet, ..} ) <$> f trustedOAuth2JwtGrantJsonWebKeySet
{-# INLINE trustedOAuth2JwtGrantJsonWebKeySetL #-}



-- * Version

-- | 'versionVersion' Lens
versionVersionL :: Lens_' Version (Maybe Text)
versionVersionL f Version{..} = (\versionVersion -> Version { versionVersion, ..} ) <$> f versionVersion
{-# INLINE versionVersionL #-}


