{-
   Ory Hydra API

   Documentation for all of Ory Hydra's APIs. 

   OpenAPI Version: 3.0.3
   Ory Hydra API API version: 
   Contact: hi@ory.sh
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : ORYHydra.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module ORYHydra.Logging
  ( module ORYHydra.LoggingKatip
  ) where

import ORYHydra.LoggingKatip

#else

module ORYHydra.Logging
  ( module ORYHydra.LoggingMonadLogger
  ) where

import ORYHydra.LoggingMonadLogger

#endif
